### ISSUE TITLE
introduce TransCommu Android SDK

### ISSUE THREAD

**Issue by tateisu** [tateisu/SubwayTooter#10]
The current number of installed users of this application is biased to Japan.
I myself am Japanese. I am poor in other languages.

I am considering introducing free multilingualization service.

TransCommu
http://transcommu.yasesprox.com/transcommu/

**Comment by tateisu** [comment]
or, Do you know more better service ?

**Comment by tateisu** [comment]
https://www.transifex.com/

https://crowdin.com/

**Comment by Belphemur** [comment]
You also have https://weblate.org/en/

You could negotiate with them to get a free hosting since you're doing an opensource/free project.

**Comment by tateisu** [comment]
TransCommu はSDK組み込みも含めて試してみたんだけど
- アプリ上の翻訳は、リソース読み込みで待たされる点以外は許容範囲
- 翻訳されたリソースをPC上で選択/ エクスポートする部分は著しく使い勝手が悪い。ダイアログっぽいのを閉じる走査があまり考慮されてない
使いたくないなー…。

**Comment by tateisu** [comment]
weblateの方がgitとの統合で便利だ、という認識になりました。閉じます。
