### ISSUE TITLE
[Misskey]ある領域からタップして会話の流れを遡ろうとすると api/note/replies に無限にリクエストしてしまう

### ISSUE THREAD

**Issue by tkmrgit** [tateisu/SubwayTooter#100]
https://misskey.io/notes/7sotawu4pe より。
https://misskey.io/notes/7sotqzie70 問題の発生個所

Misskeyの問題であれば、MisskeyにIssueを立てていただけるとありがたいです→ https://github.com/syuilo/misskey/issues

**Comment by tateisu** [comment]
fixed at https://github.com/tateisu/SubwayTooter/commit/d32777ae70c5c4d6060c94c9e01db9cea7763c8f
