### ISSUE TITLE
Wrong image height with :vertical arrange thumbnails"

### ISSUE THREAD

**Issue by Kjwon15** [tateisu/SubwayTooter#104]
If enable "vertical arrange thumbnails" in Media attachment settings, It is hard too tap "Tap to show" button and blurhash is sized wrongly.

![Screenshot_20190719-162617](https://user-images.githubusercontent.com/5047683/61517456-3ed1a180-aa42-11e9-86a4-124bfa206907.png)

**Comment by tateisu** [comment]
in case of vertical arrange, this button is used for expand/collapse thumbnails and itself is NOT thumbnail. 
then this button should not show blurhash, it's height should depends to text button.
I'll make fix it.

**Comment by Kjwon15** [comment]
So.. We cannot use blurhash with vertical arrangement?

**Comment by tateisu** [comment]
I think expand / collapse is desired in vertical arrange mode.
Also I think it's too verbose that require 2 taps foo show sensitive image, tap to expand then tap on blurhash.

**Comment by tateisu** [comment]
I tried for a while. I often misses the presence of attached media.  This needs some improvement.
