### ISSUE TITLE
Custom emoji picker displays unlisted emoji

### ISSUE THREAD

**Issue by mcmoots** [tateisu/SubwayTooter#106]
I just removed some custom emoji from my instance. When I set the emoji to "unlisted" in my instance config, it is not displayed in the web interface emoji chooser, but it is still displayed in the Subway Tooter chooser. (I refreshed the app cache before verifying this behavior.)

I think Subway Tooter should match the behavior of the web app, and not display "unlisted" emoji.

私はこれを機械翻訳しています、それがはっきりと出てくることを願っています。 混乱をおかけして申し訳ありません。

インスタンスからカスタム絵文字を削除しました。 私のインスタンス設定で絵文字を "unlisted"に設定したとき、それはウェブインターフェース絵文字セレクタには表示されませんが、それでもSubway Tooterセレクタに表示されます。 （この動作を確認する前に、アプリのキャッシュを更新しました。）

Subway TooterはWebアプリケーションの動作と一致し、「非公開」の絵文字は表示されないはずです。

**Comment by tateisu** [comment]
https://docs.joinmastodon.org/api/entities/#emoji

"unlisted" property is undocumented thing.

**Comment by mcmoots** [comment]
The relevant property is "visible_in_picker".

https://docs.joinmastodon.org/api/entities/#emoji

**Comment by tateisu** [comment]
Please check commit https://github.com/tateisu/SubwayTooter/commit/8347da397cfababa2bb9af44f22c51ce5f2b5e8c
