### ISSUE TITLE
Registering on approval-mode instance does not add account properly

### ISSUE THREAD

**Issue by trwnh** [tateisu/SubwayTooter#107]
### Steps to reproduce
0. Have an account logged in?
1. Add a new account
2. Select "Create" instead of "Log in"
3. Provide your details
4. Home column gets auto-added, with 403 error due to not approved
5. Account gets approved later
6. Home column loads properly
7. Try to add more columns, or edit account settings

### Expected behavior
- An account selector popup should let you pick between accounts

### Actual behavior
- There is no popup to select account, until you re-add the account (this time choosing "log in")

**Comment by tateisu** [comment]
reproduced.
![image](https://user-images.githubusercontent.com/333944/63646931-411bcf80-c755-11e9-82f4-b50b863d1608.png)
the account data is no correctly saved to database.
