### ISSUE TITLE
custom status bar / nav bar colors?

### ISSUE THREAD

**Issue by trwnh** [tateisu/SubwayTooter#110]
the android status bar is always grey, which can look bad with custom header bar color. maybe the status bar color should either be semi-transparent or solid.

likewise, the nav bar is always black, which looks fine but might look better if it matched the footer bar more (but i am less bothered by this)

**Comment by tateisu** [comment]
I have never seen the status bar turn grey when viewing this app on an Android 5+ devices.
what device show it?

**Comment by trwnh** [comment]
Sony Xperia X Compact (Android 8.0.0)

**Comment by tateisu** [comment]
current status bar color is same to "colorPrimaryDark", it is #303030 on light theme, or #222222 on dark theme. almost black.

>maybe the status bar color should either be semi-transparent or solid.
- In this case "transparent" has no meaning.
- I think dark grey is one of solid color. 

indeed I understand that there is a demand for customization.
However it will not offer the "Same as column header" option for the following reasons:
- There may be cases where multiple columns are displayed simultaneously in tablet mode.
- There may be no column.
- This app switches columns frequently.

and also, there is no API to set foreground color of status/navigation bar.
- some Android devices shows "light" navigations bar and its foreground is not white.

Galaxy S10+ light theme shows light gray navigation bar.
![Screenshot_20190930-040706_Subway-Tooter](https://user-images.githubusercontent.com/333944/65837994-051df080-e339-11e9-99d1-6cfe580890bd.jpg)

use setNavigationBarColor(white), the foreground is hard to be recognized.
![Screenshot_20190930-040946_Subway-Tooter](https://user-images.githubusercontent.com/333944/65838007-35658f00-e339-11e9-95d4-daa3fa500d14.jpg)

It's possible to add an option to set the color, but that would require the user to be careful.

**Comment by tateisu** [comment]
implemented at a1ca0165

**Comment by tateisu** [comment]
5feb228d

**Comment by tateisu** [comment]
5feb228d
