### ISSUE TITLE
max_idにnullが指定されていることがある

### ISSUE THREAD

**Issue by abcang** [tateisu/SubwayTooter#111]
しばしばPawooに次のようなクエリパラメータのmax_idがnullなアクセスが飛んできていてエラーが発生しています。(account_id、status_idは実際に記録されたものではないです)

`/api/v1/accounts/26/statuses?limit=80&only_media=1&max_id=null&since_id=102857430112844737`

UserAgentは`SubwayTooter/3.7.4`でした。
エラーが発生するのはPawoo側の変更が原因なのですが、本家の場合ではnullは0に変換されてSQLが実行されてしまうため、正しい結果を取得できていないと思われます。

```
pry > Status.arel_table[:id].lt('null').to_sql
=> "\"statuses\".\"id\" < 0"
```

おそらくコードのこの部分だと思いますが、時間のあるときに調査および修正をしていただけると嬉しいです。

https://github.com/tateisu/SubwayTooter/blob/eb9abf82832368397b4e9666669c6a94a9b4e7f6/app/src/main/java/jp/juggler/subwaytooter/ColumnTask_Gap.kt#L761

**Comment by tateisu** [comment]
指摘ありがとうございます。

その部分に渡されるpath_base は常に "/api/v1/conversations?limit=$READ_LIMIT" なのです。
別の原因を考えます。

TLの新しい端を差分更新した場合の挙動が以下の感じなのですが

- (A) (まだ読んでない部分)s(もう読んだ部分)  のs をsince_idとしてリクエストする
- (B) (Aで読めた部分)m (まだ読んでない部分)s(もう読んだ部分) のmをmax_id,sをsince_idとして再度リクエストする
- (C) (Aで読めた部分)(Bで読めた部分)m(まだ読んでない部分)s(もう読んだ部分) のmをmax_id,sをsince_idとしてリクエストする。読めた件数が0になるかタイムアウトまで繰り返す。

このどこかの状況でレスポンスのLinkヘッダー中のURLにmax_idがない場合が発生しているのだと思います。
この場合に期待される挙動は「リクエストを投げない、またはレスポンスに0件のデータが含まれる」です。
現状でも構わない気はしますが、API仕様nullを渡すのもよくないですね。検討します。
