### ISSUE TITLE
Completely hide toots matched by an “irreversible” filter

### ISSUE THREAD

**Issue by ThibG** [tateisu/SubwayTooter#112]
The expectation for “irreversible” filters is that the toots should never show up. However, there are edge cases were they do on Mastodon, and they will always do on Pleroma as Pleroma does not apply the filters server-side.

Dropping (or completely hiding) the toots matched by an “irreversible” filter should improve the user's experience.

**Comment by tateisu** [comment]
the description in filter UI is:

> Drop instead of hide
> Filtered toots will disappear irreversibly, even if filter is later removed

then API document is:

> Irreversible filtering will only work in home and notifications contexts by fully dropping the records. Otherwise, filtering is up to the client.

I think filter in public timeline is not irreversible and it does not drop any status.

Then there is no reason to completely hide the status.

I'm not sure where your expectation came from.

**Comment by ThibG** [comment]
People do that to not have the “Filtered” thing, mainly, and due to multiple requests, Mastodon's WebUI has been modified to completely hide those statuses a while ago.

**Comment by tateisu** [comment]
You are going to change the meaning of the flag to something different from the name.
And documentation and explanations are not keeping up.

But clients also need to support older server versions.I should not rush to deal with this matter.

**Comment by ThibG** [comment]
I am not “going to” do anything, the WebUI change has been live since v2.9.1. Server-side behavior has never changed.

**Comment by tateisu** [comment]
documentation and explanations are not keeping up.
The caption of this flag is "Drop instead of hide", but you are requesting "hide". 
Are you kidding me?

**Comment by ThibG** [comment]
Unfortunately, the API documentation cannot be kept up to date for now (it doesn't build, and Gargron doesn't care about fixing that, as another documentation website is being created at the moment, but isn't ready yet)

The description is indeed kinda confusing, but the visible effect to the end user has always been to not show the toot at all instead of a “filtered” thing, unlike with filters that don't have the “irreversible” flag turned on. Since 2.8.1, in the WebUI, this has extended to the edge cases where the Mastodon backend did not filter those.

In Pleroma, users can set filters, but they are never applied server-side, so it also makes sense to adopt this behavior, as some people rely on it.
