### ISSUE TITLE
Unavailable image linked to missing.png

### ISSUE THREAD

**Issue by Kjwon15** [tateisu/SubwayTooter#116]
For some reason, sometimes Mastodon cannot process external image and it gives missing.png and link to external url on web.
But on SubwayTooter, when user clicks that Missing image thumbnail (question mark on it), It does not going to external url and goes to local instance's "missing.png" which gives 404 Not Found

**Comment by tateisu** [comment]
"missing.png" is not found in ST's source code.
I think API response is wrong in this case.
it you encounter this problem, please open "select and copy…" and copy all status information.

also, ST's in-app media viewer has "…" menu and you can open url,remote_url,text_url on web browser.

**Comment by Kjwon15** [comment]
that "..." menu is not shown because When I click thumbnail, it try to open "missing.png" on web browser instead of opening on media viewer.
I'll post status information when I met this problem later.

**Comment by Kjwon15** [comment]
Here is the sample. Image type unknown is one of indicator maybe

```
Status-URL: https://madost.one/notes/809me6wo0a
Date: 2019-11-20 01:12:02
From-Acct: totokoro2@madost.one
Content-Warning: 헤헤 엑 헤헤 에엑

.

Media-1-Url: https://qdon.space/media_proxy/225957/original
Media-1-Remote-Url: https://media.madost.one/media/webpublic-60aa618a-cef9-4054-a1c4-75c376b7ebe9.gif
Media-1-Preview-Url: https://qdon.space/media_proxy/225957/small
Media-1-Text-Url: null
Status-Source: {"id":"103165455705382673","created_at":"2019-11-19T16:12:02.040Z","in_reply_to_id":null,"in_reply_to_account_id":null,"sensitive":true,"spoiler_text":"헤헤 엑 헤헤 에엑","visibility":"unlisted","language":null,"uri":"https:\/\/madost.one\/notes\/809me6wo0a","url":"https:\/\/madost.one\/notes\/809me6wo0a","replies_count":0,"reblogs_count":0,"favourites_count":0,"favourited":false,"reblogged":false,"muted":false,"content":"<p>.<\/p>","reblog":null,"account":{"id":"48028","username":"totokoro2","acct":"totokoro2@madost.one","display_name":"쉬익수이","locked":true,"bot":false,"created_at":"2019-10-19T13:10:36.774Z","note":"<p><\/p><p><span>인사<\/span><\/p><span>안녕하세요.<br>도수만큼 생각하고 싶습니다.<\/span><p><\/p>","url":"https:\/\/madost.one\/@totokoro2","avatar":"https:\/\/bucket.qdon.space\/accounts\/avatars\/000\/048\/028\/original\/26a23982fd02a474.jpeg","avatar_static":"https:\/\/bucket.qdon.space\/accounts\/avatars\/000\/048\/028\/original\/26a23982fd02a474.jpeg","header":"https:\/\/bucket.qdon.space\/accounts\/headers\/000\/048\/028\/original\/95753812fa861b9e.jpeg","header_static":"https:\/\/bucket.qdon.space\/accounts\/headers\/000\/048\/028\/original\/95753812fa861b9e.jpeg","followers_count":52,"following_count":73,"statuses_count":8248,"last_status_at":"2019-11-19T17:03:56.729Z","emojis":[],"fields":[{"name":"뜌부에 소속되기","value":"아무말 하세요!","verified_at":null},{"name":"닉네임 건의하기","value":"이 기능은 회원제입니다.","verified_at":null},{"name":"질문을 기부하기","value":"문질박스에 넣어 주세요!","verified_at":null},{"name":"개선을 요구하기","value":"멘션을 주세요!","verified_at":null}]},"media_attachments":[{"id":"225957","type":"unknown","url":"https:\/\/qdon.space\/media_proxy\/225957\/original","preview_url":"https:\/\/qdon.space\/media_proxy\/225957\/small","remote_url":"https:\/\/media.madost.one\/media\/webpublic-60aa618a-cef9-4054-a1c4-75c376b7ebe9.gif","text_url":null,"meta":null,"description":null,"blurhash":null}],"mentions":[],"tags":[],"emojis":[],"card":null,"poll":null}
```

**Comment by tateisu** [comment]
if media type is unknown and its url has known file extension such as jpe?g png mp4  , ST guess media type from file extension && open with in-app media viewer.  if guess failed, ST open the url in Web Browser (maybe Custom tabs).


gif is not used in guessing media type for unknown
because ST's in-app media viewer does not support GIF
because mastodon server convert gif to mp4 movie. 

for Misskey case, mediaType is used instead of Mastodon's attachment type, but  also GIF is not handled as image.

I think this is rare case and open it with a browser is enough for unknown and GIF media type. 
if the server can't handle url, it's not ST's failure.
you can consider to admin to use `tootctl media refresh`.

**Comment by Kjwon15** [comment]
Could you make it open "external url" when media type is set to "unknown" even if settings is set to "prior local url"?

**Comment by tateisu** [comment]
I think fallback to remote url is task of mastodon server because access to local server may success or may fail.
