### ISSUE TITLE
options to show why status was filtered and maybe expand it

### ISSUE THREAD

**Issue by trwnh** [tateisu/SubwayTooter#117]
when status is filtered it is replaced with just the word "filtered". it would be nice to know which filter was activated, at least. separately, sometimes you want to temporarily show a filtered post.

**Comment by tateisu** [comment]
added "app setting/ behavior/Show filtered word"
at commit https://github.com/tateisu/SubwayTooter/commit/f49ae71dd20dca5d3b4dc734676e50482cfa6523

example
https://mastodon.juggler.jp/@tateisu/103259478715139146
