### ISSUE TITLE
Option to UNDO renote

### ISSUE THREAD

**Issue by subpub** [tateisu/SubwayTooter#118]
Misskey Web does not have the option to delete a renote. I have been informed by my admin that it is possible only via API.

Can you add a option in SubwayTooter to undo a renote for misskey?

Thanks

**Comment by tateisu** [comment]
ある投稿(A)に対するRenote(B,C...)を全て解除、というAPIはありません。
ある投稿(A)に対するRenote(B,C...)を見つけるAPIはありません。
https://github.com/syuilo/misskey/issues/2353

**Comment by tateisu** [comment]
when we can see renote itself in the TL, maybe it's possible to delete its renote.

**Comment by tateisu** [comment]
implemented at https://github.com/tateisu/SubwayTooter/commit/225dbf6623ea2213aa941a2b22be5247a9a2c572

**Comment by subpub** [comment]
Wow thanks
