### ISSUE TITLE
option to hide follow and follower counts throughout application

### ISSUE THREAD

**Issue by trwnh** [tateisu/SubwayTooter#125]
i sometimes feel bad when i see that my following count has dropped or when i am interacting with someone who has a lot of followers. i think it would be beneficial to mental wellness to add a setting to hide follow and follower counts for all accounts.

**Comment by tateisu** [comment]
I will make it. but please wait…

**Comment by trwnh** [comment]
Thank you. Take your time!

**Comment by tateisu** [comment]
https://github.com/tateisu/SubwayTooter/commit/1772df949fee004e9cb21715a2968b85b59b1cc0
