### ISSUE TITLE
file_too_big error is wrong

### ISSUE THREAD

**Issue by Kjwon15** [tateisu/SubwayTooter#126]
It says "The file is bigger than the limit of 8MB" But Mastodon's image file size limit is 10MB.
How about just say something like "The file size is bigger than the limit"?

**Comment by tateisu** [comment]
- the app can't know read limitation value because Mastodon server does not disclosure those values via API.
- please check  ST's 「app settings / post / Media attachment (image) byte size limit」
- the default value is 8 because the app have to support old Mastodon server.

**Comment by tateisu** [comment]
The reason to check the size in advance is to avoid wasting bandwidth and upload time.
