### ISSUE TITLE
cannot export app data

### ISSUE THREAD

**Issue by subpub** [tateisu/SubwayTooter#129]
Android 9
version 4.0.1
Misskey

I had a language filter on one timeline, it said this. Even after removing the filter it said this.

 what do I do?

![](https://framapic.org/Wj3Z3BYCv1xA/nzVZ4lsw1luH)

**Comment by tateisu** [comment]
this is a bug of export function. fixed at https://github.com/tateisu/SubwayTooter/commit/74933a14917e32c2adfc9157c3321e40791c80ec

**Comment by subpub** [comment]
thanks
