### ISSUE TITLE
Little problem with "don't close column" option

### ISSUE THREAD

**Issue by H-F-M** [tateisu/SubwayTooter#13]
When i add a new column like opening user status or visualizing for the conversation of an user, the "don't close column" parameter switch to another column. To try this ( i have 6 columns  4 are visible, all are set with "don't close column"  option), so,  just on left column tap on user picture, this is opening his profil and the option "don't close column"  was deactivated itself on the 4th and 6th column. When i close the profile column previously opened, all option went back like at the beginning.

**Comment by tateisu** [comment]
about tablet mode ?

**Comment by H-F-M** [comment]
yes, with 4 columns visible and 2 others accessible by swiping screen. There is no problem when adding new column with the menu (on left) because it add after all others. The problem come when a column is inserted between others columns.

**Comment by tateisu** [comment]
please try 0.5.4 it will be come to store,  or you can download APK on https://github.com/tateisu/SubwayTooter/releases/tag/v0.5.4

**Comment by H-F-M** [comment]
All right now with 0.5.4 Thanks !
