### ISSUE TITLE
caching custom emoji

### ISSUE THREAD

**Issue by trwnh** [tateisu/SubwayTooter#130]
on servers with many custom emoji, i have to wait several minutes for all the emoji to load before i can find the one i want to use. this is especially true if the shortcode is further down the alphabetized list. i have to go through this every time the app is killed and restarted.

**Comment by tateisu** [comment]
I'm testing on a test server with 4096 custom emojis.
max 30MB is allocated to the custom emoji cache.
Also, ST skip send an HTTP request for update confirmation while one day after the last load.
Emoji loading is performed in 4 threads in parallel.

As a result, the current emoji picker loading speed is not much different from WebUI.

**Comment by trwnh** [comment]
on a server with 6900 custom emojis, many of which are animated, i suspect this quickly exceeds the 30MB max... given that each emoji can be up to 50KB, or even assuming just 30KB, that's about 1000 images to be loaded and then possibly discarded.

i think it is fine to say that emoji loading might take some time on the first load, but it is bad UX to have it be loaded more than once... in webUI, this load happens once, in SubwayTooter, it seems to happen whenever the app is quit.

**Comment by tateisu** [comment]
Mastodon duplicates custom emojis between servers, so the cache will grow indefinitely. How much do you think is appropriate?

**Comment by tateisu** [comment]
https://github.com/tateisu/SubwayTooter/commit/b356565057c7b367cdde53f80456e2991f43d855
in this commit :
- add a database file that cache unlimited count of custom emojis and don't refresh automatically
- add "App settings/performance/delete custom emoji cache"

using single database file for avoiding flood of many small files, but it may grow to giga bytes...

**Comment by trwnh** [comment]
Maybe allow user to set a limit on max cache size in settings? But I think the issue of duplicate custom emojis is not that big... there are probably far more emoji than there are accounts authenticated on any one user's device.
