### ISSUE TITLE
Selecting a custom Timeline font, app says existing data will be cleared

### ISSUE THREAD

**Issue by subpub** [tateisu/SubwayTooter#132]
Seems to not happen for Bold Timeline Font

Version 4.0.6

**Comment by tateisu** [comment]
this is description of import button.
> You can export data to any app that can receive data, but maybe you can import data only from device's storage or Google drive.
> Column background image may be not exported/imported over device.
> Timeline font is not exported/imported.
>Custom notification sound may be not exported/imported over device.

**Comment by subpub** [comment]
Oops, by 'importing' I meant 'Selecting' a font from app settings/appearence/Timeline Font to apply it

**Comment by tateisu** [comment]
fixed. please wait next release.
