### ISSUE TITLE
"open web page" loads empty box instead of in-app browser

### ISSUE THREAD

**Issue by trwnh** [tateisu/SubwayTooter#134]
on subwaytooter v4.1.1 attempting to open web page will just show a blank modal box with only a cancel button

**Comment by tateisu** [comment]
it's depends on some conditions.
- using custom tabs is off. (ST's app settings)
- default app for url that like toot status page is ST.
- no other app can't be listed on PackageManager#queryIntentActivities().

what web browser you expect open?

**Comment by trwnh** [comment]
whatever the default browser is? it was previously working in older release.

**Comment by trwnh** [comment]
actually i realize now that custom tabs is enabled... so the ST custom tab is not loading anymore.

enabling "don't use custom tabs" gives option of using browser of choice.

**Comment by trwnh** [comment]
i think it may be the "prioritize google chrome" option. i do not have chrome installed, but i do have chrome dev. disabling the option causes the custom tab to open normally.

**Comment by tateisu** [comment]
the option specifiy app's package name to force to use chrome to avoid app selection dialog since firefox supports custom tabs, but chrome and chrome dev has different package name.

**Comment by trwnh** [comment]
Maybe the box should say something like "Chrome is not installed" instead of being empty, then?
