### ISSUE TITLE
keep timeline position under all circumstances

### ISSUE THREAD

**Issue by mhellwig** [tateisu/SubwayTooter#138]
Maybe I did something wrong during the setup, but whenever the app has been in the background for a while (and therefore probably has been killed by the phone), when I open it, instead of seeing the last toot I saw before, I'll see the text about querying the server and so forth and then the topmost, newest post in the timeline. If this is intended behavior and there is no fix for it, I'll just use another app, no biggie, but I need to know so I can stop looking for the config option I missed...

**Comment by tateisu** [comment]
when other foreground apps request RAM, the Android OS will discard background process.
Then when the app resume to foreground, the app can restore the data that was saved to disk before the app went to the background.
But ST's current implementation does not save the timeline date to disk in any timing. They are kept only in the process's RAM. When the process is destroyed and restored as described above, ST just reloads the timeline.

I know this approach has pros and cons.
ST can handle lots of timelines with lots of columns, so saving to disk can be expensive. 
Also, the stored timeline complicates management such as "when should it be discarded" and "when should be updated to the latest state (deleted toot, or inserted toot by delayed arrival from federation)".

This issue has been investigated for some time, but has not been closed.

**Comment by tateisu** [comment]
Also, the "timeline sort order" required by the Mastodon API cannot be supported by the sort order provided by SQLite database. As a result, queries that retrieve the timeline stored in the app's internal database in the correct sort order can be quite expensive.

**Comment by mhellwig** [comment]
thank you for the detailed explanation!

hmm. 

alternative idea, afaict any post has a unique ID in the form of a URL that points to it, right? Would it not be possible to just save that URL and upon reload scroll the timeline back down to it?

**Comment by tateisu** [comment]
Vanilla Mastodon has only 400 posts for each Home/List TL on the server. This limit does not exist in the public TL, but in any case, the client can get about 20 posts per request. sending many requests for many columns when screen resume will significantly slow down client responsiveness , and also  it makes error by rate-limit throttling.

**Comment by mhellwig** [comment]
thanks again, closing the issue
