### ISSUE TITLE
Custom emoji in categories not showing

### ISSUE THREAD

**Issue by snoozysoft** [tateisu/SubwayTooter#139]
Hi,

On Awoo.space, custom emojis have categories to help keep them ordered. This is a feature in the "Glitch" fork of Mastodon. Subway Tooter doesn't seem to be able to display them as a result. Tusky can pull them in fine, for reference. 

![Screenshot_20200514-122827](https://user-images.githubusercontent.com/48827511/81929300-b595e780-95de-11ea-9633-b00740404fac.png)
![Screenshot_20200514-123027](https://user-images.githubusercontent.com/48827511/81929307-b9c20500-95de-11ea-85e4-30c148a89ba6.png)

**Comment by tateisu** [comment]
creating account on Awoo.space is pending review by their staff.

**Comment by tateisu** [comment]
awoo.space requires authentication in https://${instance}/api/v1/custom_emojis .
this API should be "public" that described in https://docs.joinmastodon.org/methods/instance/custom_emojis/ .

please consider to admin of your server.

**Comment by tateisu** [comment]
![image](https://user-images.githubusercontent.com/333944/82118727-1de9f200-97b4-11ea-8c51-70af0b899e8e.png)

https://awoo.space/api/v1/custom_emojis returns 401 for ST's request.
but this API should be open that described in https://docs.joinmastodon.org/methods/instance/custom_emojis/ 

please consider to admin of your server.

**Comment by snoozysoft** [comment]
Hi, Awoo is a bit of a special instance in that its more closed off than usual for the sake of safety from harassment and similar things. The custom emoji api is a thing that is allowed to be closed off as it is part of Mastodon's "allow list" feature. As i previously mentioned, Tusky ( https://github.com/tuskyapp/Tusky ) is able to retrieve custom emojis from Awoo due to proper implementation of this feature.

**Comment by tateisu** [comment]
what about Mastodon's "allow list" feature ?

**Comment by tateisu** [comment]
Gargron says 
> The feature isn't called "allow list", it's whitelist mode. It combines "secure mode" with whitelist-based federation. Secure mode means apps cannot use the API without user context. This should be OK in your case, you just need to authenticate the request for custom emojis the same way you do other requests for a logged in user.

**Comment by snoozysoft** [comment]
Yeah, sorry, whitelist is what I meant. Gargron's advise there should hopefully fix the issue.
