### ISSUE TITLE
F-Droid “error in opening zip file”

### ISSUE THREAD

**Issue by Anmibe** [tateisu/SubwayTooter#141]
I added the repo for f-droid at
<https://android.izzysoft.de/repo/apk/jp.juggler.subwaytooter>. F-droid accepted the url, but gives an error when opening the zipped index file.

Perhaps due to missing signature?

**Comment by tateisu** [comment]
IzzyOnDroid has copied the APK from release page of this GitHub, but I'm not related in it at all.
You should contact to IzzyOnDroid.

**Comment by Anmibe** [comment]
Found the problem. The url on your git hub page <https://android.izzysoft.de/repo/apk/jp.juggler.subwaytooter> doesn’t work.

Using instead the url from the LizzyOnDroid site <https://apt.izzysoft.de/fdroid/repo?fingerprint=3BF0D6ABFEAE2F401707B6D966BE743BF0EEE49C2561B9BA39073711F628937A> works fine.
