### ISSUE TITLE
"the browser app is not installed" and "no apps can open url" when chrome stable is not installed

### ISSUE THREAD

**Issue by trwnh** [tateisu/SubwayTooter#147]
i have firefox nightly and chrome dev installed, but tapping on browser links fails to open. this seems to happen with youtube links especially.

i have tried enabling and disabling "don't use custom tabs when opening links" and no difference. "prioritise google chome" is turned off.

**Comment by tateisu** [comment]
maybe supported at 18c4245a31520ea1848330a530651ae6ef894ff0

**Comment by trwnh** [comment]
confirmed fixed. thank you!
