### ISSUE TITLE
Multiple tag filters not working

### ISSUE THREAD

**Issue by ryliejamesthomas** [tateisu/SubwayTooter#148]
Hi. Since the latest update (4.3.9) the tabs I have open that use multiple tags no longer work. I get the error:

`loading failed.: IllegalStateException encodeQuery: unsupported type java.util.ArrayList`

If I change the query to use only one tag it works fine.

I'm using both 'Additional tags: any' and 'Additional tags: none', in different tabs.

Recreating the tag search/query does not help.

**Comment by tateisu** [comment]
Thank you for the report. I'll investigate.

**Comment by ryliejamesthomas** [comment]
Latest update works great, thanks!
