### ISSUE TITLE
Misskey のリアクション後につく背景色を変更したい

### ISSUE THREAD

**Issue by kintsuba** [tateisu/SubwayTooter#150]
現状 Misskey でリアクションを付けた後の背景色（以下の画像の水色部分）について、設定から変更できないように見受けられます。

![Screenshot_20210130-090632](https://user-images.githubusercontent.com/20216486/106339740-d7550d00-62da-11eb-8f25-983804fa84dd.png)

リアクションはよく使う機能なので、見た目に与える影響も大きめだと思います。
ご検討のほど、よろしくお願いいたします。

**Comment by tateisu** [comment]
https://github.com/tateisu/SubwayTooter/commit/4cf16c6ee890a7d492cd90bf9bc68dffff879e9d で対応。そのうちリリースされるでしょう。

**Comment by kintsuba** [comment]
ご対応ありがとうございます！
