### ISSUE TITLE
Unable to log into whitelist_mode instance

### ISSUE THREAD

**Issue by snoozysoft** [tateisu/SubwayTooter#155]
![photo_2021-05-08_17-58-20](https://user-images.githubusercontent.com/48827511/117547358-1a83f200-b027-11eb-811a-bc8ddb6f3524.jpg)

I have made a new single user instance for myself. It's in limited federation (aka allowlist/whitelist) mode and also the "AUTHORIZED_FETCH" variable is enabled in my environment for the server. In theory, no app should have trouble with this. The expected behaviour for me is for it to pop open a browser window with the login page to said instance; wherein I'll log in, authorize the app and everything is good. Tusky works that way, for example. But attempting to do this with Subway Tooter just results in the error message "This method requires an authenticated user (HTTP 401) <URL> GET /api/v1/isntance". Checking the specific URL that the app is looking for just presents me with basic information about said instance; why does it need to look for this first? Surely just by checking the site itself it can intuit that it's a Mastodon instance and open up the relevant browser page from there?

It's also quite a baffling error to receive since the app is asking for an authenticated user that it can't get...because it wont let me add an authenticated user.

**Comment by tateisu** [comment]
このユースケースは今まで十分に検討されていなかったことです。
我々は何かできることがないか検討します。

STは複数のサービス(Mastodon,Misskey)と過去のバージョンの挙動の違いに対応しているので、ログイン前にインスタンス情報を確認することは必須です。

**Comment by snoozysoft** [comment]
Yeah, fair that this hasn't come up often if at all. Regarding checking the instance type, an alternative method could be letting the user pick what software the instance runs in the event that the app can't check the relevant information page?

**Comment by tateisu** [comment]
アプリはログインする前にクライアント登録を行います。
クライアント登録のパラメータの１つである機能スコープの内容はサーバのバージョンによって異なります。
2.4.0rc1 以降は "read+write+follow+push"、それより古いサーバでは "read+write+follow" です。
(TuskyはPush通知をサポートしないので、常に "read write follow"を使います。)

**Comment by tateisu** [comment]
AUTHORIZED_FETCH が追加されたのは 3.0.0なので、インスタンス情報APIが401を返した場合はスコープ指定は"read+write+follow+push"だと仮定できます

**Comment by snoozysoft** [comment]
Ah, I think I see what you're saying. So ST checks the /api/v1/instance page to see what version the server is on so it knows how to register the application? So if it's above version 2.4.0rc1, it registers for push notifications, but if its below that then it doesn't bother with push? 

So the fix is just as simple as assuming it can register for push notifications if 401 is returned when the app tries to check the instance? That's definitely a lot simpler than I expected, haha.

**Comment by snoozysoft** [comment]
Thanks so much for sorting the issue out so quickly!
