### ISSUE TITLE
Subway Tooter requests grant type "client_credentials" when trying to connect to Friendica

### ISSUE THREAD

**Issue by annando** [tateisu/SubwayTooter#156]
I'm currently implementing the Mastodon API at Friendica. At the moment I'm testing several apps against it.

In Friendica we only implemented the grant type "authorization_code" - and according to the source code it seems as if Subway Tooter does use it when connecting to Mastodon servers.

I tried to connect to my Friendica server with Subway Tooter. Does the following two requests:
```
"POST /api/v1/apps HTTP/1.1" 200 3587 "-" "SubwayTooter/4.5.1 Android/10"
"POST /oauth/token HTTP/1.1" 422 562 "-" "SubwayTooter/4.5.1 Android/10"
```

The second requests fails from our side since the grant type is set to "client_credentials" (which we don't support). But in the source I saw that the grant type "authorization_code" is used as well from Subway Tooter.

For me it seems as if in the function `prepareClientMastodon` the application decides which grant type to chose. What can I do from my side to persuade Subway Tooter to only use the grant type "authorization_code"?

**Comment by tateisu** [comment]
Should ST make a 422 error at that timing?
user sign IN may work. I haven't tried it.

(anyway user sign **UP** doesn't work because client_credential is required for it)

**Comment by annando** [comment]
Thanks for the ultra fast reaction!
