### ISSUE TITLE
Feature request: Filter notifications client-side based on relationship

### ISSUE THREAD

**Issue by trwnh** [tateisu/SubwayTooter#161]
The official Mastodon iOS app has a setting for notifications like so:

Notify me when [anyone / a follower / anyone i follow / no one]:

- favorites my post
- follows me
- reblogs my post
- mentions me

One way to do this better than the official Mastodon iOS app would be to have a policy per type, and to support mutuals too. I think you can do this with client-side filtering. When ST receives a push notification, check the type, then check the notification policy.

For example, you receive a favorite notification, then check the app settings / configuration to see that the policy is "anyone i follow". You then show the notification if it is indeed from someone you follow, or you do not show it if it is from someone you do not follow.

**Comment by tateisu** [comment]
![Screenshot_20210817-122002_Subway Tooter](https://user-images.githubusercontent.com/333944/129658548-53698bf7-fb50-4e7e-9b07-9bfd48601fa1.jpg)

do you talk about this?

**Comment by trwnh** [comment]
Yes, but separated by notification type. For example:

Type | Policy
--- | ---
Favorites | Anyone I follow
Boosts | Mutuals
Mentions | Anyone
Follows | None

**Comment by tateisu** [comment]
I am willing to support it, but the time will be delayed due to private reasons.

**Comment by trwnh** [comment]
that's fine. Thank you for everything you do for this client, it remains
and continues to be the best way to use the fediverse on any platform.

**Comment by tateisu** [comment]
With ST 5.512 I've revamped our push notification support, and I've noticed:
- API accept policy parameter for all alerts, not policy per alert.
- WebPush message does not contain acct of notification.user. then app can't know who triggered about notification.

**Comment by trwnh** [comment]
related mastodon issue: https://github.com/mastodon/mastodon/issues/22943
