### ISSUE TITLE
対応リンクが有効になるURLが開けない

### ISSUE THREAD

**Issue by qunaud** [tateisu/SubwayTooter#162]
![Screenshot_20210822-141144](https://user-images.githubusercontent.com/13547972/130343370-bf10df15-fd4f-4d2f-ac89-06baeee9590b.png)
YoutubeやAmazon,Pixiv等のアプリへの対応リンクが指定されている場合、対応するアプリがインストールされてるのにも関わらず開けない
TwitterはTwitterアプリが立ち上がる模様
Ver.4.5.2で症状を確認、それ以前から出ていそう

**Comment by tateisu** [comment]
対応する意思はあるけど、プライベート都合で時期は遅れます。

**Comment by tateisu** [comment]
supported at 18c4245a31520ea1848330a530651ae6ef894ff0
