### ISSUE TITLE
[question]アカウント削除方法はあるか

### ISSUE THREAD

**Issue by yumetodo** [tateisu/SubwayTooter#176]
Mastodonのインスタンスの一つであるQiitadonを長らく利用してきましたが、2月末にサービス終了を迎えました。

ここで、qiitadonのアカウントをsubwaytooterから除去しようと考えたのですが、アカウント設定画面などを見たものの、その方法が見つかりませんでした。

そういった手段はありますか？

![Screenshot_20220302-115611](https://user-images.githubusercontent.com/10869046/156287735-28432aa5-bd71-41b9-96d5-126e87aed237.png)

**Comment by osapon** [comment]
アカウントの設定の中にありますね。
<img src="https://i.gyazo.com/80765cc698b8d0089de9ddbcd2e27639.png">

**Comment by yumetodo** [comment]
見落としていました、ありがとうございました。
