### ISSUE TITLE
Option to configure max size of message instead of forced 500 chars. (per server/instance)

### ISSUE THREAD

**Issue by seachdamh** [tateisu/SubwayTooter#177]
Describe

A option for every server/instance I use where I can configure max message limit. It is annoying on mastodon/pleroma instances where a lot of it have custom message limits to be closed in "default" 500 chars.
Why

I general it would be best if instance reported own limits but as I know in case of mastodon authors aren't keen to sutch idea.
But still fact is a lot of servers admin change it and there is really a lot of instances with 512/600/5000/10000 message limits. It is simply annoying constantly go between web intrerface to write longer answer and program.

Default can be set on current 500 char as standard rule.

**Comment by tateisu** [comment]
> I general it would be best if instance reported own limits but as I know in case of mastodon authors aren't keen to sutch idea.

- `max_toot_chars` is provided on some customized instances.
- mastodon 3.4.2 has configuration entity in api/v1/instance. https://github.com/mastodon/mastodon/pull/16485

also. ST's account setting already has max toot chars that is used if avobe information is not provided from server.

**Comment by tateisu** [comment]
Furthermore, the number of remaining characters is just a guide, and ST does not validate by the number of text chars.
(server side will check it.)

**Comment by seachdamh** [comment]
Oh, good to know. It is sort solution also.
