### ISSUE TITLE
画像を貼るとエラー表示され添付されない。

### ISSUE THREAD

**Issue by pupu1366** [tateisu/SubwayTooter#178]
投稿画面にて画像を添付しようとした際に下記写真のエラーが表示され添付が出来ません。
リサイズ設定は設定しており、他の端末で撮った写真は投稿できています。

![Screenshot_20220313-220823](https://user-images.githubusercontent.com/11733716/158182951-ef4031f3-0323-4aef-b1f5-65a43073a210.png)

使用端末：sharp leitz phone1
OS：android11
subwaytooter：4.8.2

**Comment by pupu1366** [comment]
adb logcatを行いましたが、あまりにも情報が多く何を出力すれば良いのか分かりませんでした。ご教授いただければと思います。

**Comment by tateisu** [comment]
表示されるエラーは
- 画像を圧縮しようとして多分何か失敗してる(A)
- 圧縮失敗したらオリジナルのまま投稿しようとする(B)
の(B)の部分が表示されてますね。

(A)の部分を取得するのは
- `adb logcat | grep -i subway >log.txt` などでlog.txtに出力し続ける状態にする
- 問題となる操作を行う
- adb logcat を CTRL+C などで止める
- log.txt をzipしてissueに貼り付ける
などの手順になるかと思います。

**Comment by pupu1366** [comment]
logの出力が出来ました。ご確認よろしくお願いします。
[log.zip](https://github.com/tateisu/SubwayTooter/files/8248817/log.zip)

**Comment by tateisu** [comment]
メモ。
```
03-15 07:28:42.013  3389  3435 D SubwayTooter:BitmapUtils: createResizedBitmap: no need to resize or rotate
03-15 07:28:42.013  3389  3435 W SubwayTooter:AttachmentUploader: createResizedImageOpener failed. fall back to original image. :IllegalStateException createResizedBitmap returns null.
03-15 07:28:42.033  3389  3435 D SubwayTooter:TootApiClient: request: POST https://mstdn.tamag.org/api/v2/media
```
内部でリサイズ指定がうまく渡ってないか、画像サイズの取得に失敗してる…？

**Comment by tateisu** [comment]
(A) image_matrix_limit を元にResizeConfigを作る部分で平方ピクセルとピクセルを混同してるバグがあった。
(B) 特にカスタマイズしていない https://mastodon.juggler.jp/api/v1/instance の image_matrix_limit は 16777216 
(4096x4096) だけど、実際に4096x4096の画像をWebやSTから投げてもサーバ側でさらにリサイズされた。この数値を目安としてクライアント側でリサイズしてもサーバ側リサイズをスキップできないので、3.4.2以降でもアカウント設定のリサイズ指定を尊重するようにした。

**Comment by tateisu** [comment]
https://github.com/tateisu/SubwayTooter/releases/tag/v4.8.3 を用意したので、リリースページの Assets にある SubwayTooter-main-rc-483-4.8.3-20220315_142758.apk を端末にダウンロードしてアップデートしてみてください。

**Comment by pupu1366** [comment]
投稿してみたところ問題なく画像添付できました。
お手数をおかけしました。ありがとうございます。
