### ISSUE TITLE
-idea- concerning BG pictures

### ISSUE THREAD

**Issue by H-F-M** [tateisu/SubwayTooter#18]
Another idea come to me, can we have a check box to mirroring background image (like Vertical mirror) to have a better visual effect without 2 different pictures ( 'q'|'p' ... 'q' is an image, 'p' is the same image mirrored), maybe you can think about this ...

**Comment by tateisu** [comment]
Do you say same thing for OS for multiple monitor PC ?
I think it's overkill.

**Comment by H-F-M** [comment]
No just background pictures, only on multi-column mode Ex: if you have a BG pict who have a specific design on the 1st column and you put the same at the 2nd column i mean a possibility to accord these picture to have 1st column unchanged and 2nd mirroring picture otherwise the right part of second picture come on the left side and the left side come to right side, then these look  accorded.  (qp ... 1st 'q' is left image and 'p' is the same image mirrored at the next column).

**Comment by tateisu** [comment]
It's overkill. Most applications do not have such functions even if it has skin system.

**Comment by H-F-M** [comment]
Surely but I have the right to hope ... I understand that you want to do in simplicity but it could have been fun as a function if it had been simply possible without too much complicating life ^^
