### ISSUE TITLE
unsupported notification type 'admin.sign_up'

### ISSUE THREAD

**Issue by ryliejamesthomas** [tateisu/SubwayTooter#181]
There's a new notification for admins that gets sent when a new account is approved.

Currently Subway Tooter provides this message:

> unknown notification from [user]
>
> notification type is admin.sign_up

Mastodon web UI provides:

![screenshot_22-04-06_12-26-24](https://user-images.githubusercontent.com/25972447/161884450-d0a1012a-a8f6-46b2-8628-c80b306d0579.png)

(Similar to notification sent when a user follows you)

**Comment by tateisu** [comment]
supported at 77be9f9396eee9a2e3ee5cef71c80857a1c73615
