### ISSUE TITLE
Feature: Support for alt-text on Misskey

### ISSUE THREAD

**Issue by EvelynSubarrow** [tateisu/SubwayTooter#182]
Hello! I use Subway Tooter as my main mobile client for Misskey, I have at least one blind person following me, and I'd like to be able to describe the images I post for him using alt-text. The option for setting mastodon description doesn't work on Misskey, and shows a 404 error

https://misskey.io/api-doc#operation/drive/files/create
I think it's the field here labelled "comment"

Thank you!

**Comment by tateisu** [comment]
closed by  e18212749430012015d394fed799f2dbf9b2a3b6

**Comment by EvelynSubarrow** [comment]
Thank you very much
