### ISSUE TITLE
Galaxy Tab S6 で「暗い」UIテーマでも背景が白くなる

### ISSUE THREAD

**Issue by tateisu** [tateisu/SubwayTooter#186]
メールによる報告

> 端末による問題の可能性が大きいのですが Android１２の端末（GalaxytabS6）をライトモードで利用していると、Subwaytooterがその影響を受けてしまうようでダークモード利用時でも背景が真っ白になってしまいました。
> Androidをダークモードにすれば一応解決しますし、Subwaytootarの設定で内容の背景色を黒にすれば概ね（最下部のみ白い帯が残る）解決はするのですが、アプリ側の不具合かもしれないのでお伝えしておきます。

**Comment by tateisu** [comment]
Galaxy Tab S6 は手持ちのがあるので検証してみました。- Galaxy Tab S6 (Android 12,セキュリティパッチレベル2022年3月1日)
- 端末の設定の「ディスプレイ」の頭にあるテーマ選択は「ライト」
- STの「アプリ設定/色/UIテーマ」は「暗い」
- 他の設定はすべて初期状態
- 結果：再現せず

![Screenshot_20220529-140552_Subway Tooter](https://user-images.githubusercontent.com/333944/170853180-137fe24b-2fe1-4753-8b57-41eca28d8390.jpg)


何か再現条件に心当たりがあるようでしたらお知らせください。

**Comment by motorailgun** [comment]
この現象ですがGalaxy Tab S7でも以前から発生しています。割とランダムに起こるので発生条件がわからないのですが、
- 一度起こるとアプリを閉じて開き直しても継続する
- ↑に「おそらく」スリープは関係していない
- 発生条件がランダムにすら思えるほど不明
- 起きたあとしばらく端末を使わないでいたり、別のアプリを使っていると解消することがある
と言った感じです。ご参考までに……。

**Comment by tateisu** [comment]
Galaxy固有の現象で、再現性がなく、原因もワークアラウンドも不明。
直しようがないです。

**Comment by LZMAShili** [comment]
再現性ありとして再報告します。
- Galaxy S22 Ultra (Android 13,セキュリティパッチレベル2022年11月1日)
- 端末の設定の「ディスプレイ」の頭にあるテーマ選択は「ダーク」
- STの「アプリ設定/色/UIテーマ」は「暗い」
- 他の設定はすべて初期状態
- 結果：再現性あり、ただし条件付き
条件：
1. アプリが終了(タスクマネージャーでキル、またはOS側で自動終了、または「設定」からの強制終了)された後の次の起動で発生
2. アプリ内「アプリを終了」を実施後すぐの起動ではダークテーマが反映される

暫定対応策：
- 背景色をUI色設定と同じく16進数で設定できるようにする

https://user-images.githubusercontent.com/121721874/210945633-5e8edc81-9e23-4769-8806-2be88012910b.mp4

**Comment by tateisu** [comment]
ユーザ側は「内容の背景色」を指定することで現象を回避できるということでしょうか？

**Comment by tateisu** [comment]
https://github.com/tateisu/SubwayTooter/commit/08a45804e7cbc567ea4f8ae2ff196dafdcf68462

**Comment by LZMAShili** [comment]
そうですね。
ここで「一応」と記述したのは、ジェスチャーナビゲーション使用時のナビゲーションバー部分も白くなっているため、根本的な解決になるかは怪しいと考えています。

**Comment by tateisu** [comment]
原因究明できるかどうかは「私の手元で再現できるかどうか」が大きいですが、できてないです。

**Comment by tateisu** [comment]
Build.MANUFACTURER に samsung が含まれるならrootViewに背景色を指定する（余計な描画が１回増える)
https://github.com/tateisu/SubwayTooter/commit/08a45804e7cbc567ea4f8ae2ff196dafdcf68462
を組み込んだAPKを用意しました。お試しください。
https://m1j.zzz.ac/tateisu/SubwayTooter-main-rc-505-5.0.5-20230106_203026.apk

**Comment by LZMAShili** [comment]
動画の通り、問題なく動作していることを確認しました(ナビゲーションバー部分も問題なく黒色になっています)。

https://user-images.githubusercontent.com/121721874/211005984-135e1dfd-0596-4293-a885-9dab8ed76ce5.mp4

**Comment by tateisu** [comment]
確認ありがとうございます。じゃあコレでいきますか…
