### ISSUE TITLE
Set default posting language to "Follow web" instead of "device language"

### ISSUE THREAD

**Issue by tribela** [tateisu/SubwayTooter#187]
People are confusing this. because they set their posting language to "XX" on web setting, But ST keep posting "YY" language.
Currently ST don't have language code option in posting UI, So it is not expected behaviour and people cannot know there are posting language setting.

Please set default posting language to "Follow web setting" same as posting privacy setting.
Or, Add language selector on posting UI so people know what language code they are using

**Comment by tateisu** [comment]
Is web settings are exposed on client API ?

also, see "account setting" instead of "app setting".

**Comment by tribela** [comment]
If don't send `language` parameter, that is following web setting. like `visibility` parameter

**Comment by tateisu** [comment]
implemented at d8005577966689bc889dec84930654db587c6d3d
