### ISSUE TITLE
"Post button was tapped repeatedly"

### ISSUE THREAD

**Issue by snoozysoft** [tateisu/SubwayTooter#189]
Hi,

I'm running version 4.8.6 on my phone right now. At some point between this release and the last version I was using before updating (unsure which, but I have to imagine the previous stable release since I get the app through Google Play), this error/warning was added to the app. It seems that there's some kind of weird rate limit-style message going on where I can't make a new post within a certain amount of time after the last post. I'm rather confused by it since this was never a problem in the previous versions, so why is it showing up now? It's become a thorn in the side of both me and my friends who also use the app.

**Comment by tateisu** [comment]
please check 4.8.7

**Comment by snoozysoft** [comment]
Initial tests seem to indicate it being fixed in 4.8.7. I'll comment again if the issue happens again. Thank you!
