### ISSUE TITLE
cannot post from misskey: "misskey does not allow duplicate in attachments" despite no attachments

### ISSUE THREAD

**Issue by trwnh** [tateisu/SubwayTooter#190]
SubwayTooter 4.8.7 and I think 4.8.6 have this bug where I cannot post from Misskey without an attachment. every time i try to post it fails with the message

error: misskey does not allow duplicate in attachments

adding an attachment makes this error go away and i can successfully post from misskey. but i would rather not have to attach a meaningless image every time just to post ^_^;

**Comment by tateisu** [comment]
sorry, fixed.
