### ISSUE TITLE
UI improvements for media descriptions 

### ISSUE THREAD

**Issue by cadadr** [tateisu/SubwayTooter#193]
Hey, thanks for this great app, my favourite fedi client by far!

I want to make a couple suggestions/feature requests to improve the UI for typing up media descriptions.

Currently the relevant popup is just a single line of text.

I think two changes would improve this a lot (and this is also how Tusky does it):

1. Adding a small, zoomable preview of the media in the media description popup.

2. Replacing the single line media input in the said popup with a multiline one, like a <textarea> in HTML.

**Comment by cadadr** [comment]
this "attachment description" dialog box:

![Screenshot_2022-11-20-10-40-45-832_jp juggler subwaytooter](https://user-images.githubusercontent.com/9742985/202892234-3a7f74d2-df01-4019-815c-164f0483a132.jpg "a modal dialog in the Subway Tooter app")

**Comment by tateisu** [comment]
b6f30f0097a2c9393e5522c8c8e6905df4d8d34b
