### ISSUE TITLE
GIF photo is converted to PNG

### ISSUE THREAD

**Issue by trwnh** [tateisu/SubwayTooter#196]
I try to upload a GIF which I expect will become an animation once uploaded to Mastodon, but instead it is a PNG static image.

**Comment by rszasz** [comment]
Seconded. Subway tooter lets me pick gifs from Gboard, but converts them to static pngs. Even after turning off image resize and video transcode options

**Comment by tateisu** [comment]
https://github.com/tateisu/SubwayTooter/commit/f2ee75502d76eb13cb49f8401ff7fc51ca7d7b0d
- don't compress GIF image

**Comment by tateisu** [comment]
https://github.com/tateisu/SubwayTooter/releases/tag/v5.0.4
