### ISSUE TITLE
Uploading .m4a AAC results in "no video stream" 422 error from /api/v2/media

### ISSUE THREAD

**Issue by trwnh** [tateisu/SubwayTooter#197]
official mastodon app can accept m4a audio with aac encoding, but subway tooter for some reason fails with 422 error

**Comment by tateisu** [comment]
https://mastodon.juggler.jp/@tateisu/109881003457637953
I tried m4a and that is uploaded no problem.

![image](https://user-images.githubusercontent.com/333944/219709418-6d3a5c95-aee6-409c-86a4-f3c13b27c1bb.png)

**Comment by tateisu** [comment]
secondary I tried 2.4MB text.m4a ( converted from mp3 using foobar2k)
it could uplloaded

**Comment by trwnh** [comment]
i do not remember which file i used that had this issue, so i will close the issue for now and reopen it if i can replicate it
