### ISSUE TITLE
option to decrease boost/favorite/reply icon sizes

### ISSUE THREAD

**Issue by ChristopherWMartin** [tateisu/SubwayTooter#2]
I find the current size of these icons distracting and it would be nice if the sizes were configurable.

**Comment by tateisu** [comment]
In the design guideline, touch target size is defined as at least 48dp.
https://material.io/guidelines/layout/metrics-keylines.html#metrics-keylines-touch-target-size

Current width/height of  boost/favorite/reply button is 40dp .
Already slightly small.

I feel better way is make  "simplified view" option that use different layout xml applied to elements of ListView. In simplified view, all buttons will be removed  and tap list item to open pop-up menu to show those buttons.

Or, really do you want more small button ?

**Comment by ChristopherWMartin** [comment]
I feel like having the option to change them in settings would be a good idea. If thats not possible a simple view would be a very nice idea as well. I just find myself a bit distracted by the ui elements as they are now.

**Comment by tateisu** [comment]
simplified view was implemented.
https://mastodon.juggler.jp/@tateisu/656899

**Comment by ChristopherWMartin** [comment]
I just updated, it looks great! Thank you for all of the quick updates. Closing this issue.
