### ISSUE TITLE
search column placeholder tries to load deprecated v1 api

### ISSUE THREAD

**Issue by trwnh** [tateisu/SubwayTooter#201]
mastodon.social gives a 404 for api/v1/search because it has been replaced with api/v2/search, making it impossible to search from subway tooter

**Comment by tateisu** [comment]
ST will try v2 first and if response code indicates error , then try v1. 

https://github.com/tateisu/SubwayTooter/blob/dc8148b3d17c439d20373d0f83443d2c6ec08bae/app/src/main/java/jp/juggler/subwaytooter/api/TootApiClient.kt#L1281

https://github.com/tateisu/SubwayTooter/blob/406ce8e5c522fb8982a2776f98b250caee54997e/app/src/main/java/jp/juggler/subwaytooter/column/ColumnTask_Loading.kt#L1226

**Comment by trwnh** [comment]
ahh, it seems the search works but the placeholder is incorrect and misleading 
![Screenshot_20221029-121233](https://user-images.githubusercontent.com/10606431/198841878-6d2dd5b6-b6b4-4e1f-bbd4-b817c5197694.png)

**Comment by tateisu** [comment]
in this case, both of v2 and v1 have been failed.
Perhaps the conditions under which the app should fall back from v2 to v1 should be narrower (e.g., fall back to v1 only if v2 returns a 404), but I am not clear on that.

**Comment by trwnh** [comment]
i think v2 search requires a user token now, so it probably returns 401.
not completely sure though, haven't tested it yet

**Comment by tateisu** [comment]
if parameter q is famous tag,  mastodon.social returns tags with plot, it
means v2 search succeeded.
I think the behavior of v2 search was  changed if parameter q is empty.

2022年10月30日(日) 6:24 trwnh ***@***.***>:

> i think v2 search requires a user token now, so it probably returns 401.
> not completely sure though, haven't tested it yet
>

**Comment by tateisu** [comment]
19d626e5f101b778230e3af2a46052e832ec01b7
- dont send empty search request.

**Comment by tateisu** [comment]
https://github.com/tateisu/SubwayTooter/releases/tag/v5.0.4
