### ISSUE TITLE
Regular notification sounds but no notification message

### ISSUE THREAD

**Issue by boyddensmore** [tateisu/SubwayTooter#204]
Hi!  First, thank you for this awesome app.  I use it daily and am glad I found it :)

Symptom:

1. When I have the app open I'm fairly regularly getting 3-4 notification sounds play, but no notifications pop up.
2. I am not doing anything in the app when the sound plays, which makes it seem like a refresh or other automated process.
3. My notification sound is playing but its volume is controlled by the Ringtone volume setting.  If I have Ringtone up and Notification silent I hear the sound.  If I have Notification up but Ringtone silent I do not hear it.
4. When I'm in Notification Settings I do not hear the sound.

What I've tried

1. In each of my accounts I've changed the Notification style (Android 8.0+) from Alert to Silent.
2. In System Settings, turned off notifications globally for the whole app.

System specs

- Phone, Galaxy S9, SM-G960W
- App version 5.0.3
- Android 10

I don't know when this started, I've ignored it for quite a while.
Thanks again!

**Comment by boyddensmore** [comment]
Ahaa!

I guess I just had to search your code repo for Ringtone.  I see that highlighted words can have notification sounds that are fired as ringtones.

Maybe this could be an enhancement request for these to be handled as notifications instead, but if you would rather just close it I'm OK with that too!

**Comment by tateisu** [comment]
- In OS's app info os ST, notification channel "realtime notifier" may configured with sound.
- Also, as you pointed out, keyword highlighting may makes sounds. 

Especially with multiple accounts, the user has difficulty to find target message when receiving keyword highlighting sound.
so maybe keyword highlighting should give a notification or show the highlight history.
