### ISSUE TITLE
feature: configurable background color for filtered posts

### ISSUE THREAD

**Issue by roycewilliams** [tateisu/SubwayTooter#208]
When reading through posts, it would be very useful to visually distinguish more clearly between filtered posts and unfiltered posts.

Since other elements of the interface have configurable colors (which is excellent and much appreciated!), It would be very useful to be able to figure this also. In the Mastodon official web interface, the colors for filtered posts are slightly more faded, etc. but different people have different needs, So making this a configurable option would probably scale best.

As you can probably see, I am using filters a lot ... and really enjoying this app.Thank you for your work on it - it is very helpful for my life and work!

**Comment by tateisu** [comment]
About keyword filters?
Filters are for hiding content.
I don't quite understand the need to highlight with a background color for the "filtered posts" that does not shows content.
What kind of display do you want?

**Comment by roycewilliams** [comment]
Since both filtered posts and unfiltered posts are exactly the same color, and can have many words in them, when you are reading quickly, they look very similar. If the filtered posts had a different background color, it would be easier to differentiate them.

**Comment by roycewilliams** [comment]
If it is easier, instead of a customizable background color, enabling the user to select a different font or font size might also work well. Or even font style, perhaps changing the filter words to be italics, for example.

**Comment by tateisu** [comment]
0e28b9d7167b4d9be0c422873805e1ec6e9a549b
