### ISSUE TITLE
[Bug] Simplified Chinese users may cannot switch to the corresponding language automatically

### ISSUE THREAD

**Issue by wuhang2003** [tateisu/SubwayTooter#210]
When opening the app, Simplified Chinese users cannot automatically switch to the corresponding language. (Even when using more locale 2)
And it's not just me, there is a similar situation in the [comments](https://github.com/tateisu/SubwayTooter/issues/154#issuecomment-835661753) of the issues and other feedback from the Chinese community.

Original Language:
简体中文用户在打开软件时无法自动切换到对应语言（即使是使用 More locale 2 也无法切换）
而且不止是我，在原来 issues 的[评论](https://github.com/tateisu/SubwayTooter/issues/154#issuecomment-835661753)以及其他来自中国社区中的反馈中均有类似情况。

**Comment by tateisu** [comment]
端末が简体中文をサポートしている場合に、アプリが中文を表示できるようにするべきだと思います。
アプリの文字列リソースは res/values-cn/strings.xml でしたが、これをどのように変えるべきでしょうか。

https://developers.helpshift.com/android/i18n/
の表の「values」の列で、最も適切なものを選んでください。

**Comment by tateisu** [comment]
https://github.com/tateisu/SubwayTooter/commit/4ba61b86cef8d64b7f45d8436befbf00538a512e

**Comment by tateisu** [comment]
https://github.com/tateisu/SubwayTooter/releases/tag/v5.0.4
