### ISSUE TITLE
option to use filled icons again

### ISSUE THREAD

**Issue by trwnh** [tateisu/SubwayTooter#216]
the new outline icons in 5.0.6 are hard for me to visually parse. i preferred the old filled icons much more

**Comment by tateisu** [comment]
It's the type of request that increases maintenance costs.
Will I be forced to prepare multiple icon images every time I add a new feature?

**Comment by tateisu** [comment]
5.0.6 uses https://materialdesignicons.com/ .
But a few years later version maybe use https://fonts.google.com/icons more thin outline.

**Comment by trwnh** [comment]
> It's the type of request that increases maintenance costs. Will I be forced to prepare multiple icon images every time adding new feature?

i understand that it is hard to have two icon sets. personally i would only use filled icons. i only said "option" in case anyone actually wants outline icons.

the reason i prefer filled icons is because they are easier on my eyes: 
![image](https://user-images.githubusercontent.com/10606431/211631064-f57705f1-4f88-4321-a9c8-d8ffe6f66df4.png)

**Comment by tateisu** [comment]
In real world, many apps goes to use outline style for their action icons.
As I understand, it's way to align the weight of texts and icons.
No one wants to fill the alphabet.
