### ISSUE TITLE
画面分割の下側か右側で、投稿をタップしたときのポップアップの位置がずれる

### ISSUE THREAD

**Issue by lo48576** [tateisu/SubwayTooter#217]
## 環境
* Subway Tooter 5.0.7
* Android 12 (ビルド 61.1.D.2.267)
* 端末: Xperia 5 Ⅲ

記憶が定かではありませんが、最近導入された問題ではなく、だいぶ前 (2年以上前？) から存在しています。

## 現象
以下のいずれの画像も、画面内に見える最初の (一番上の) 投稿をタップしたときの様子です。

正常: 上側、左側
![top pane](https://user-images.githubusercontent.com/1246590/212143958-0076b5ec-f632-4706-82f3-84341843061f.png)
![left pane](https://user-images.githubusercontent.com/1246590/212143973-10ce3135-51b9-4497-afd2-860be82f1ea3.png)

異常: 下側、右側
![bottom pane](https://user-images.githubusercontent.com/1246590/212144094-06eb0e50-ffb6-4595-80ab-bf7da252fd9c.png)
![right pane](https://user-images.githubusercontent.com/1246590/212144117-a58d8324-e820-4225-88b1-ffa0ee85ce12.png)

 SubwayTooter が下側にあるとき、ポップアップメニューがかなり下側にずれて表示されています。
また右側にあるときにも、ポップアップが画面右端に貼りついており、おそらく同様の原因で右へ大幅にずれている (ものが、しかし画面外には飛び出さず補正されて表示されている) ようです。

**Comment by tateisu** [comment]
f182d2438ce872dfc24966443d86237b91542f2f

**Comment by tateisu** [comment]
https://github.com/tateisu/SubwayTooter/releases/tag/v5.0.8
