### ISSUE TITLE
Redraft and delete destroys post with Mastodon v4

### ISSUE THREAD

**Issue by cadadr** [tateisu/SubwayTooter#219]
ST v5.0.7 on Redmi 7, MIUI Global 11.0.2, Android 10

When I redraft and delete from an instance with Mastodon v4, after I hit post, I get a 404 record not found error, and the post is lost.

**Comment by tateisu** [comment]
After reading it, I test it on 2 servers.

4.0.2 https://mastodon.juggler.jp/@tateisu/109713651698035201
3.5.3 https://mastodon2.juggler.jp/@tateisu/109713660854980219

'edit' and 'redraft & delete' can keep media attachment on these servers.

any information of server sat can reproduce problem?

**Comment by cadadr** [comment]
i can't seem to reproduce this issue now. i reckon it was something temporary. closing, sorry

fwiw it was on scholar.social, vanilla mastodon on a mastodon SaaS
