### ISSUE TITLE
webp download(save) feature changes its filename extension

### ISSUE THREAD

**Issue by tribela** [tateisu/SubwayTooter#223]
version: 5.510
Step to reproduce:
1. Open an image with webp extension
2. Tap save button
3. filename.webp is saved as filename.web

Expected behaviour: saved as same filename
Actual behaviour: saved with different filename (I think it cut off file extension by 3 letters)

**Comment by tateisu** [comment]
![image](https://user-images.githubusercontent.com/333944/215357260-8006752e-27b7-41c8-8bc2-a5cb89e76b91.png)

id+ext is clipped into 20 chars. 🤔

**Comment by tateisu** [comment]
https://github.com/tateisu/SubwayTooter/commit/0955dff8db15e6285b780ffae68a1717f1df71e1
