### ISSUE TITLE
has the edit post option moved or been removed?

### ISSUE THREAD

**Issue by pswilde** [tateisu/SubwayTooter#226]
Hi,
I was just wondering if "Edit" has been moved from "your toot" or removed from the app completely? I just can't see it any more.
I noticed it vanished when updating from 504 to 507 of Subway Tooter. Currently on 5.511 and it still isn't there (though I can see "Edit History").

Thanks for the app though, I love it!

**Comment by tateisu** [comment]
can you see pencil icon in 「…」more menu for each post?

2023年2月7日(火) 18:41 Paul Wilde ***@***.***>:

**Comment by pswilde** [comment]
Hi,
No, I do not. I only see the following: 
![image](https://user-images.githubusercontent.com/31094984/217239585-335ae540-92b8-41fd-9c92-a6c69674e5a7.png)  
Under "Your Toot" I only see "delete and redraft", "pin on profile" and "delete"
I should say I am using Pleroma, not Mastodon, which is likely where this problem is cropping up. It worked fine on version 504 and previous though so I know the functionality should work - just the option is missing.

**Comment by pswilde** [comment]
I see, OK thanks. Looks like it's only allowing editing on Mastodon v3.5.0rc1 and above. That makes sense.
OK, if I get time I'll see if I can make it work without affecting things too much and submit a pull request. 
Thanks for your help

**Comment by tateisu** [comment]
I'm saved. To be honest, I don't really understand Pleroma's versioning in
api/v1/instance.

2023年2月7日(火) 21:18 Paul Wilde ***@***.***>:

**Comment by pswilde** [comment]
I agree. The versioning in Pleroma is not good - even worse if you think about Akkoma and Rebased too.
However It does have in /api/v1/instance a `pleroma: metadata: features` node with one available string item being "editing" so it's probably worth checking that as an option to enable editing.

**Comment by tateisu** [comment]
The feature list is one thing Mastodon lacks.
 I knew Fedibird kept a list of additional features, but I didn't know
Preloma had it too.

2023年2月7日(火) 21:39 Paul Wilde ***@***.***>:

**Comment by tateisu** [comment]
8a6ad18ba7ce4d8363dfe280922404adfb7cceec 
changed, but not tested.

**Comment by pswilde** [comment]
Looks good!
I'd be happy to test this, though for some reason I'm unable to compile SubwayTooter myself (I dont really do app development, I probably have a configuration error somewhere).
if this is in the next pre-release then I'll report back whether it works or not

**Comment by tateisu** [comment]
check github release page, that is already included.

2023年2月11日(土) 3:48 Paul Wilde ***@***.***>:

**Comment by pswilde** [comment]
oh yes, i see now, i needed to look at the tags list.
 yep, v5.514 is working perfectly. thank you!

**Comment by tateisu** [comment]
thanks!
