### ISSUE TITLE
per-ABI builds?

### ISSUE THREAD

**Issue by IzzySoft** [tateisu/SubwayTooter#229]
May I kindly ask for per-ABI builds of the noFcm flavor (and to let me know whether to pick the armeabi then or the arm64)? Background: APK size is already beyond the per-app limits of my repo (which is 30 MB). Further, as a single ARM build will probably be less than 15 MB it would allow me to keep 2 versions again, which prevents "update errors" (when a new release was pushing out the old one, but the user has not yet updated the index). Thanks in advance!

**Comment by tateisu** [comment]
it's not so effective. I try adding splits abi configuration to build.gradle and generated APK size is:
```
$ ls -lt  app/SubwayTooter*.apk
-rwxrwx---+ 1 tateisu None 32025023 Feb 11 21:19 app/SubwayTooter-main-fcm-x86-515-5.515-20230211_211849.apk
-rwxrwx---+ 1 tateisu None 31722547 Feb 11 21:19 app/SubwayTooter-main-fcm-arm64-v8a-515-5.515-20230211_211848.apk
-rwxrwx---+ 1 tateisu None 32263509 Feb 11 21:19 app/SubwayTooter-main-fcm-x86_64-515-5.515-20230211_211849.apk
-rwxrwx---+ 1 tateisu None 39239454 Feb 11 21:19 app/SubwayTooter-main-fcm-all-515-5.515-20230211_211848.apk
-rwxrwx---+ 1 tateisu None 38541446 Feb 11 21:18 app/SubwayTooter-main-nofcm-all-515-5.515-20230211_211825.apk
-rwxrwx---+ 1 tateisu None 31327015 Feb 11 21:18 app/SubwayTooter-main-nofcm-x86-515-5.515-20230211_211826.apk
-rwxrwx---+ 1 tateisu None 31024539 Feb 11 21:18 app/SubwayTooter-main-nofcm-arm64-v8a-515-5.515-20230211_211825.apk
-rwxrwx---+ 1 tateisu None 31565501 Feb 11 21:18 app/SubwayTooter-main-nofcm-x86_64-515-5.515-20230211_211826.apk
```

it you doubt, please try open APK file with zip archive manager, delete unwanted architecture in lib/ . its result is almost same to above.

mainly reason of app size is
- including many emoji data. 
- names and unused resources not be shurinked for trouble shooting purpose.
![image](https://user-images.githubusercontent.com/333944/218258015-79f7f7c5-55b3-4383-ac59-ea5961f7d544.png)

**Comment by tateisu** [comment]
Universal builds also have advantages, as users may not always understand the ABI. 
If we don't get the effects that was looking for, I'd like to continue with the universal build.

**Comment by IzzySoft** [comment]
Umpf, I should have digged in deeper. My calculation was "the usual case" with a lot of libraries taking up at least 10 MB per ABI. Cases where assets are the cause are rather rare, so I forgot to check for that. Anyway, thanks for trying! I fully agree then, weighing the pros and cons, the cons clearly outweigh the pros.

Let's look at another possibility: [minification](https://github.com/tateisu/SubwayTooter/blob/main/app/build.gradle#L77). Would you consider [Minify android app but do not obfuscate it](https://stackoverflow.com/q/35853593/2533433) – or did you already try that and it didn't work out?

**Comment by tateisu** [comment]
![image](https://user-images.githubusercontent.com/333944/235348091-2190ec50-fbd9-4f1f-88ac-2c539b155a2c.png)

ST's app size is 7.71MB lower than the median of similar apps at 38.7MB.

**Comment by IzzySoft** [comment]
> ST's app size is 7.71MB lower than the median of similar apps at 38.7MB.

With or without minification? Remember the size limit in my repo is 30 MB per app, and I need to keep exceptions as few as possible. The APK currently in my repo is, as you pointed out, 38 MB – and thus already beyond the limit. So did you try to [Minify android app but do not obfuscate it](https://stackoverflow.com/q/35853593/2533433)? Do you see any downside to that approach? How much space did it safe with ST?

**Comment by tateisu** [comment]
This number is the size of the currently published app.
It shows that it is not particularly large compared to other apps of the same genre on the Play Store.

**Comment by IzzySoft** [comment]
While that might be the case, it's over the size limit of my repo – so I'd usually remove the app as it grew too much. I don't measure by Playstore means – and that there are bigger apps is no argument, sorry. So let me ask once more: can the size be reduced? If not, I might have to remove the app one day, which I'd rather not – so I'd much prefer you help me keep it :wink:

**Comment by tateisu** [comment]
I actually enabled R8 and tried to build. APK size remained almost the same. This is a change for the forecast. I'm not going to adopt it and do extensive testing against it. I have reverted this change.

**Comment by IzzySoft** [comment]
Thanks! Cannot ask for more. And agreed, 5% saved isn't the outcome I've hoped for.

To sum app: neither per-ABI-builds nor minification would significantly reduce APK size. That's an argument I only can (and have to) accept. Thanks for giving it a try! I'll then add SubwayTooter to my "exception list" for now. May I ask you to fix the link in the Readme then? The package name in the link to my repo lacks the `.noFcm` suffix, so the link currently gives a 404.

**Comment by tateisu** [comment]
updating readme is done at https://github.com/tateisu/SubwayTooter/commit/cfee3771a6cdf85bf9ee46cd2a7527c83fe33736

**Comment by IzzySoft** [comment]
Thanks again!
