### ISSUE TITLE
option to group system notifications like they used to be

### ISSUE THREAD

**Issue by trwnh** [tateisu/SubwayTooter#230]
a recent build of subway tooter now shows one system notification for every account notification, when previously it only showed one system notification for every account (and all notifications were grouped under that one system notification). can we go back to that? i don't want to be flooded by notifications

![Screenshot_20230211-001925](https://user-images.githubusercontent.com/10606431/218244064-8ae44441-da06-4a93-b841-b2160954215d.png)

**Comment by tateisu** [comment]
A1: open account setting, off push notification and on pull notification check. it's old implementation.

A2:
This change regarding the handling of push notifications is
- Do not access REST API when notification occurs
- Display notifications with only the information contained in push notifications
This policy was implemented.

The current implementation does not aggregate multiple notifications.
- There may be multiple workers processing push notifications running at the same time, and we need to arbitrate between them.
- It is necessary to scan the in-app DB and reissue already issued notifications.
- Some want expressiveness per notification.

Probably, I think that the appropriate direction is to use the notification group function provided by the OS. https://developer.android.com/develop/ui/views/notifications/group

**Comment by tateisu** [comment]
https://www.reddit.com/r/GooglePixel/comments/qqxy6k/no_grouped_notifications_in_android_12/
since Android 12 notification grouping is not working...

**Comment by tateisu** [comment]
https://www.reddit.com/r/GooglePixel/comments/x6cl0i/android_13_notification_grouping/

**Comment by tateisu** [comment]
seems just adding group summary notification works as "delayed grouping" ??

**Comment by tateisu** [comment]
963dc4edec6fa44fb57f8fa09cbbbcd2663374e4 
added group summary notification. maybe it works fold notifications "at delayed"

**Comment by tateisu** [comment]
https://mastodon.juggler.jp/@SubwayTooter/109846253362190025
released on 5.516, it works.
