### ISSUE TITLE
Problems with friendica istances

### ISSUE THREAD

**Issue by emilio-millepiani** [tateisu/SubwayTooter#234]
Hi!

In the release 5.517 and 5.518 it's impossible to add a new accont for two Friendica istances: poliverso.org and rizomatica.org.
In the four pictures you can see...Thank you for your work and the wonderful app.

![Screenshot_20230217-125844_Trebuchet](https://user-images.githubusercontent.com/74871181/219649664-75ee2496-d5e2-4f9e-b7a0-4e4992a236eb.png)
![Screenshot_20230217-125857_Trebuchet](https://user-images.githubusercontent.com/74871181/219649660-509e5d6b-ffa5-4974-912d-32ad112c0a59.png)

![Screenshot_20230217-125933_Trebuchet](https://user-images.githubusercontent.com/74871181/219649710-6a61a259-197c-4b77-809f-4e319b744bbe.png)
![Screenshot_20230217-125945_Trebuchet](https://user-images.githubusercontent.com/74871181/219649706-0210c794-6fd7-4bff-beb1-5f5825a66baa.png)

**Comment by tateisu** [comment]
for some reason, when getting server information , ST try /api/meta(misskey) 1st, then if it returns 404 , try /api/v1/instance(mastodon).

**Comment by emilio-millepiani** [comment]
But is this a problem with Friendica servers or ST? Up to two previous versions it didn't happen. can it be fixed?
Thank you in advance.

**Comment by tateisu** [comment]
I think friendica choose incorrect HTTP response code.

also, I tried to create account on specified sites from PC browser, but both not available now.
I can't check about /api/v1/apps/verify_credential .

**Comment by tateisu** [comment]
Mastodon server may returns 401 for server information, it means "this server is whitelist mode".
Misskey server NET YET returns 401 for server information, but it's not guaranteed.
If ST parse response code 401 to "this is not Misskey server", then ST may choose incorrect on the future.

but if try both and one returns server information, maybe ST can use it.

**Comment by tateisu** [comment]
some changes about server information , I could login and post from https://xn--c9j1b.xn--r9j630glz6a.xn--q9jyb4c/profile/tateisu/profile

**Comment by tateisu** [comment]
thanks to  @hanubeki@fedibird.com with https://fedibird.com/@hanubeki/109880867897184393

**Comment by tateisu** [comment]
https://ぜひ.一緒に.みんな/display/88ed63bd-1563-f0a2-6ad3-dfa501742715
