### ISSUE TITLE
(Mastodon) starts_atがnullでないようなお知らせ(Announcement)を、starts_atの時刻以前にも表示してほしい

### ISSUE THREAD

**Issue by takayamaki** [tateisu/SubwayTooter#235]
いつも使わせていただいております、 imastodon.netのフサギコです。

要約すると掲題の通りなのですが、現在のSubwayTooterの実装では `/api/v1/announcements` を通じて取得できるお知らせ(Announcement)について、そのstarts_atに日時が入っている(nullでない)場合に、starts_atの日時を過ぎないとSubwayTooterのホームTLのお知らせ欄に表示されないという挙動になっているのではないかと思います。

マストドン管理者画面におけるAnnouncementの入力画面では、starts_at(予定開始日時)とends_at(予定終了日時)は「お知らせを用いて告知するイベント等の対象期間を入力する」欄として提示されており、掲載を開始したい日時はscheduled_at(掲載予約日時)として別に存在します。
なお、scheduled_atは `/api/v1/announcements` で配信されるjsonには含まれていません。

![image](https://user-images.githubusercontent.com/24884114/221695582-8df7dfb2-a253-45ad-8925-b5e7a91c2d44.png)

また、マストドンのユーザ向けwebUIにおいても、scheduled_atの時刻をもって掲載を開始し、ends_atの時刻をもって掲載を終了する挙動になっていました。

上記スクリーンショットのようなサービス断を伴うようなメンテナンスの告知でstarts_atを入力した場合に、starts_atの日時を過ぎるまで表示されないのは告知漏れとなってしまうため、こちら挙動の変更をご検討いただけますと幸いです。

当該の挙動が発生したバージョン: 5.522
当該の挙動が発生した時刻: 2023/02/25 00:20～2023/02/26 01:00(上記管理画面スクリーンショットのお知らせのstarts_at)

以上です、宜しくお願いします。

**Comment by tateisu** [comment]
ありがとうございます。確認します。

https://docs.joinmastodon.org/methods/announcements/ 
https://docs.joinmastodon.org/entities/Announcement/
scheduled_at ないですね…

**Comment by tateisu** [comment]
https://docs.joinmastodon.org/entities/Announcement/ には
「starts_at Description: When the announcement will start.」 とあるが、admin UI では「Start of event: Optional. In case your announcement is bound to a specific time range」となっている

**Comment by tateisu** [comment]
- APIから取得可能なのはpublish済みのイベントだけなので、事前にイベント告知開始時間を知ることはできない
- WebUIはストリーミングで告知開始イベントを受け取る
- 画面OFF中にストリーミングを受け取れないモバイルアプリは画面をONにするたびに /api/v1/announcements を読み直す必要がある…？

**Comment by tateisu** [comment]
8184ad5693a74fd86c083440cc9f14e4fb0178ab

**Comment by takayamaki** [comment]
対応ありがとうございます！
