### ISSUE TITLE
Download all content of a user(add new feature)

### ISSUE THREAD

**Issue by Stu75e** [tateisu/SubwayTooter#245]
Please put a solution in the program to download all the posts, including photos and videos of other users, so that when there is no access to the Internet or when a person has sent educational materials, etc., all the contents of the person can be downloaded in full.

**Comment by tateisu** [comment]
What is the reason for doing it with a mobile app?
That's a request minor enough to feel complicated.
I believe that request use PC and the network environment that cost not depends on the transfer amount.

**Comment by tateisu** [comment]
also, Since ST handles so many columns, it omits even saving the posts themselves in the in-app DB.

**Comment by tateisu** [comment]
I think it's not job for a normal mobile client app.

2023年7月23日(日) 20:17 Wjxfi ***@***.***>:

**Comment by tateisu** [comment]
If I do that, I write a crude script myself that run on PC.

So I haven't looked into existing tools.

**Comment by tateisu** [comment]
This kind of scraping tool will always be criticized, which puts a heavy burden on the person who published the tool.
