### ISSUE TITLE
10MB以上の添付メディアについて

### ISSUE THREAD

**Issue by KOBAYAN99** [tateisu/SubwayTooter#246]
最近、VivaldiSocialで写真投稿をする際に添付のエラーが出るようになりました。以前は出ていなかったのですが、仕様でしょうか。
![Screenshot_20230521-022551](https://github.com/tateisu/SubwayTooter/assets/132152140/5007f7bc-0a50-42ed-967b-34ff99210bda)

環境：Android　12
端末：Xperia5Ⅲ

写真は下記をあげようとしていました。
![20230521_015945](https://github.com/tateisu/SubwayTooter/assets/132152140/70e8a77a-25e0-41f3-92a4-072e3c47116f)

**Comment by tateisu** [comment]
5.532をお使いでしょうか？

2023年5月21日(日) 3:04 KOBAYAN ***@***.***>:

**Comment by KOBAYAN99** [comment]
5.529です。

**Comment by tateisu** [comment]
https://github.com/tateisu/SubwayTooter/issues/242 類似したissueがあって、その修正が入ったのが5.531以降です。
Playストアはまだ審査が通っていませんが、必要ならGitHubのReleaseページで最新版のAPKファイルを端末にインストールすることで更新できます。

**Comment by KOBAYAN99** [comment]
最新版をインストールしたところ、アップロードできることを確認しました。
ありがとうございました。
