### ISSUE TITLE
画像投稿について

### ISSUE THREAD

**Issue by joubousou** [tateisu/SubwayTooter#247]
最新バージョン5.532で画像をアップロードしようとすると以下のようなメッセージが出てしまいます。
![Screenshot_20230523-133502](https://github.com/tateisu/SubwayTooter/assets/134358236/4f5fbfd1-9c57-40b5-8aad-3ba3bbbb194a)
5.529たと問題無かったのですが。

**Comment by tateisu** [comment]
https://mastodon.juggler.jp/@SubwayTooter/110414087557380596

**Comment by tateisu** [comment]
アップロード前にST側で画像をリサイズする際に使われる画像フォーマットを、「可能ならWebPを使う」ように5.531で変更されました。「可能なら」はサーバ側の対応フォーマット一覧をみて判断しています。

しかし mstdn.jp はサーバのセットアップに問題があり、WebPに対応しているという情報があるのですが、実際にアップロードすると500エラーになります。WebUIでWebP画像をおくることでも問題が再現されます。これはmstdn.jp固有のバグです。

ST的には設定画面でオプションを変更することでWebPへの変換を行わないようにできます。
