### ISSUE TITLE
FOSS build no longer fully FOSS

### ISSUE THREAD

**Issue by IzzySoft** [tateisu/SubwayTooter#249]
My updater just sent me a warning that the last release brought in a couple of proprietary components:

```
Offending libs:
---------------
* Firebase Data Transport (/com/google/android/datatransport): NonFreeNet
* Google Cast (/com/google/android/gms/cast): NonFreeDep
* Google Mobile Services (/com/google/android/gms): NonFreeDep
* Firebase (/com/google/firebase): NonFreeNet,NonFreeDep

4 offenders.
```

No idea why you include Google Cast with a Mastodon client, but I suspect that was the culprit dragging in the other 3 (Cast depends on GMS at least, not sure about Firebase. Any chance you could exclude those for the `noFcm` flavor as well? Meanwhile, I have to add back those anti-features until this is solved. Thanks in advance for your help with this – my experience from last time gives me hope this will be solved as well :smiley:

**Comment by tateisu** [comment]
thank you for notice.
that dependency is came from `androidx.media3:media3-cast:1.1.0` and I will remove it at next release.

**Comment by tateisu** [comment]
5.537 released.

**Comment by IzzySoft** [comment]
Ah, thanks! Then let me pull that in manually now and we can skip having the AntiFeatures show up… Yupp, confirmed: all gone – wonderful, that was blazingly fast!
