### ISSUE TITLE
Loading screen doesn't shows up 

### ISSUE THREAD

**Issue by expertmanofficial** [tateisu/SubwayTooter#259]
Link to video recording: https://cdn.discordapp.com/attachments/738199053728350260/1199856680855425074/Subway_Tooter.mp4?ex=65c4109c&is=65b19b9c&hm=10301d59bda9e4b57d539b99d5e3ee0ec8a36091e1e0f70ad545e0604211bbc9&

**Comment by expertmanofficial** [comment]
![294644998-7412928f-a3b9-4a5d-b1ea-1df13760d51f.jpg](https://github.com/tateisu/SubwayTooter/assets/119038242/a051fc64-2b22-4ba2-afcc-228dd59881f1)

This my Android phone information in case you need.

**Comment by tateisu** [comment]
that splash screen shown by OS was introduced on Android 12.

**Comment by expertmanofficial** [comment]
hmmmm, ok. Can you make it compatible with Android 11 as well?

**Comment by tateisu** [comment]
I guess you just don't want to see a white initialization screen on a dark theme screen.

https://github.com/tateisu/SubwayTooter/commit/ab094216d3dd38112d17abf622ad2a0c4508f000
