### ISSUE TITLE
Suggestion about activity resume

### ISSUE THREAD

**Issue by H-F-M** [tateisu/SubwayTooter#26]
Is it possible to have an option like "dont_refresh_on_activity_resume" but to scroll the column automatically to the last published toot ("scroll_up_on_activity_resume") ?
Please !! :)

**Comment by tateisu** [comment]
"resume" means also back from child activity. for example, open "selection and copy" and press back button, it raises "resuming main activity". I think this situation user want keep current reading position.

**Comment by tateisu** [comment]
Application can not detects  events such as ( home button pressed / task switch button pressed / lock screen shown ), just knows when activity is pause / resume .

**Comment by H-F-M** [comment]
Ok, thread closed then ..
