### ISSUE TITLE
[Sharkey] Viewing an image and then hitting "back" reloads the column

### ISSUE THREAD

**Issue by fossmanjack** [tateisu/SubwayTooter#261]
**Version:** 5.545
**Device:** Motorola Moto G Stylus 5G
**Android:** 13

### Behavior

When viewing an image on a column associated with a Sharkey account, and then pressing "back" to exit the image, the column reloads.

### Expected Behavior

When viewing an image and then pressing "back", the column should not reload.

**Comment by tateisu** [comment]
ST does not save/restore  column content to flash memory, then if OS
destroy the main screen that is triggered by memory management, ST reload
each column content.

Also, ST does not have the ability to automatically shrink column content,
so killing processes and recovering from memory pressure serves as a
substitute.







2024年4月21日(日) 14:18 Jack Meyers ***@***.***>:

**Comment by fossmanjack** [comment]
The thing of it is, this is only happening with Sharkey columns -- I can look at images, open threads, browse to other tabs, without always losing my place in Mastodon or Pleroma columns.

However, I was able to resolve the issue by selecting "Disable auto-refresh when returning to the app" in the column tab.  Workaround works for me.

**Comment by tateisu** [comment]
auto-refresh is a function that requests to server for more new data from the current top of the column.
For this to work correctly, the API response must include the appropriate `prev` URL in the `Link:` header at previous loading. In your case, the server has not implemented it properly.
