### ISSUE TITLE
Since 0.6.4 auto-refresh home column don't work well

### ISSUE THREAD

**Issue by H-F-M** [tateisu/SubwayTooter#42]
Hello,
I still have to make a slide down to refresh the "house" column. It does not automatically do it as before version 0.6.4, it can be a consequence related to the correction of the bug # 36. The other columns work correctly, I do not understand why only "home" is a problem.

**Comment by tateisu** [comment]
auto-refresh at activity resume?
or manually pull-to-refresh ?

**Comment by H-F-M** [comment]
"Not auto-refresh at activity resume".
Before, I just slid down the column and it automatically updated afterwards. But now when I slide down, it refreshes once and then nothing, I have to redo it every time. While other columns function normally as before.

**Comment by H-F-M** [comment]
i've tried with v0.6.0, v0.6.2, v0.6.3 and is the same problem with "home" TL, no automatic refresh, federated TL and others work well ..
I do not know what to think, before it worked and now it does not work anymore ... it is possible that it does not come from Subway Tooter but a mastodon's server problem  ... i do not know.

**Comment by tateisu** [comment]
It can not be reproduce. 

I'd try following sequence.

- running latest code on Nexus 7 2013 
- show home column ,it's column setting is all clear.

- show device's home button to pause activity
- show the app to resume activity
- (toot from another device, another account that will be shown on home)
- it was shown in real time via streaming api 

- pull-to-refresh 
- (toot from another device, another account that will be shown on home)
- it was shown in real time via streaming api

**Comment by tateisu** [comment]
also I've check adb log.
There was no abnormality in the connection status of Streaming API

`/adb logcat -v threadtime |grep -a StreamReader`
(or if using Android Studio, open Android monitor / open logcat tab / set filter as StreamReader )

- when activity paused
```
05-23 01:35:05.386 11670 11976 D SubwayTooter: StreamReader: WebSocket onFailure. url=https://mastodon.juggler.jp/api/v1/streaming/?stream=user&access_token=*** :SocketException Socket closed
05-23 01:35:05.389 11670 12138 D SubwayTooter: StreamReader: WebSocket onFailure. url=https://mastodon.juggler.jp/api/v1/streaming/?stream=user&access_token=*** :SocketException Socket closed
05-23 01:35:05.391 11670 12123 D SubwayTooter: StreamReader: WebSocket onFailure. url=https://mastodon.juggler.jp/api/v1/streaming/?stream=public:local&access_token=*** :SocketException Socket closed
(snip)
```

- when activity resumed
```
05-23 01:35:07.888 11670 12123 D SubwayTooter: StreamReader: WebSocket onOpen. url=https://mastodon.juggler.jp/api/v1/streaming/?stream=user&access_token=***
05-23 01:35:07.899 11670 12138 D SubwayTooter: StreamReader: WebSocket onOpen. url=https://mastodon.juggler.jp/api/v1/streaming/?stream=user&access_token=***
05-23 01:35:07.956 11670 11976 D SubwayTooter: StreamReader: WebSocket onOpen. url=https://mastodon.juggler.jp/api/v1/streaming/?stream=public:local&access_token=***
05-23 01:46:42.070 11670  2750 D SubwayTooter: StreamReader: WebSocket onOpen. url=https://mastodon.juggler.jp/api/v1/streaming/?stream=user&access_token=***
(snip)
```

**Comment by H-F-M** [comment]
Thanks for your investigations.
For my part, I have just been able to test the different version of subway tooter at my disposal, the column "home" does not want to scroll automatically, I am obliged to update it by sliding down every time. I will make a small video to show this, I will put it at your disposal as soon as possible.
Cordially.

**Comment by H-F-M** [comment]
Hi,
it's been 2 days since the problem disappeared, everything works as before, it lets me confirm that the origin of the bug was not related to "Subway Tooter" but to the instance to which I am bound. I did not have the presence of mind to connect with another account when the problem was present and it's a shame. So since this "issue" no longer needs to be, I close it.
