### ISSUE TITLE
WANTED: server owner who can runs streaming-listener server

### ISSUE THREAD

**Issue by tateisu** [tateisu/SubwayTooter#46]
Subway Tooter supports Real-time notification via Firebase Cloud messaging.
But it is confined to a few instances.
Because it depends on external streaming-listener server.

If there is who can runs https://github.com/tateisu/mastodon-streaming-listener for a instance
and configure it to cooperate with Subway Tooter,
we can support Real-time notification  for that instance.

**Comment by aschmitz** [comment]
Do you know the rough resource requirements for running this server for the public? (I'm setting it up for my personal instance, but if it isn't too intense, I may be able to open it up.)

**Comment by tateisu** [comment]
mastodon has push subscription.
