### ISSUE TITLE
mistake ...

### ISSUE THREAD

**Issue by H-F-M** [tateisu/SubwayTooter#48]
how to delete this ?

**Comment by tateisu** [comment]
indicator means visible range.

2017/05/27 20:22 "H.F.M" <notifications@github.com>:

**Comment by H-F-M** [comment]
Yes, i've seen that just after writing issue ... 

Thanks anyway :)

**Comment by tateisu** [comment]
Github does not provide function of deleting an issue.
https://stackoverflow.com/questions/3081521/how-to-completely-remove-an-issue-from-github
