### ISSUE TITLE
not an issue jsut about plugin list ...

### ISSUE THREAD

**Issue by H-F-M** [tateisu/SubwayTooter#50]
plugin list doesn't appear when plugin already present. Ok it's your choice but,
in case of lambda user when i try a plugin, i test it and after 10 mins i decide it's useless, i want to pick another but (remember i'm a simple user) no list appear ... i turn around and after a little time, i remove previous and hope the list of others plugin appear again ...

I think you would make a place of plugins list in option list (at the end) and when no plugin was installed (seems the first time) you make a "goto" to this list, in this way plugins list is always present if needed.

What you think about that ?

**Comment by tateisu** [comment]
ap more menu in posting screen

2017/05/28 午後7:50 "H.F.M" <notifications@github.com>:

**Comment by H-F-M** [comment]
ahah !! well done ^^ (i'm simple user ...)
