### ISSUE TITLE
Changes list in Play Store also in english language

### ISSUE THREAD

**Issue by auge8472** [tateisu/SubwayTooter#51]
As an european without any knowledge in japanese language I'm not able to read your list of recently changes in the description of the app. Is there any possibility to add an english version of the changes list?

**Comment by H-F-M** [comment]
Hi, Auge
I'm like you, Japanese languague is a mysterious things. However i use google translate between Jap/Eng to understand the changes list, it 's not perfect but this let me understand a bit the modifications. I've tryed Jap/Fre but the resultat was undicernable ...

**Comment by tateisu** [comment]
I think my engRish capavility is poorer than Google translation :)

Kidding,

My english writing is verrrrry slow. It becomes a burden of release work.
I hope someone translates release information and shares it.

**Comment by H-F-M** [comment]
@tateisu if you find a way to translate from Japanese to English i can translate properly to French so.

**Comment by auge8472** [comment]
> I hope someone translates release information and shares it.

With "Google Translate" as basis of a translation (in my case to german and english language) as proposed by @H-F-M, it could generally be done. How you as the project maintainer want's to inform the translators and gets the translations *prior to the releases*? How to handle this?

The ready translations (or parts of it) can be given through pull requests. But how to inform the translators beforehand? Maybe an issue with translators mentioned?

**Comment by H-F-M** [comment]
@auge8472 
actually i maintain the french translation of SubT "strings.xml", after an update, i checking that file to see if it was changed and if it's the case i put french translation in it, then he's available in next version of SubT after merging.

In fact, for the update information, some times google translate don't do the job when specific context (knowledge about Mastodon's network or programming specific expression) and give us fake information of the real concerned subject (I sometimes need @tateisu to have a more specific explanation in order to establish a good translation in the context).

In case of update information, i don't really know how to proceed, as you, i ask for @tateisu to indicate a good solution to provide translation with minimum delay.

**Comment by tateisu** [comment]
this issue is beyond the scope that I can deal with,
If you have complaints please fork and deal with it yourself

**Comment by H-F-M** [comment]
Ok, for me, it's simple, when i know a new version is available, i'm going here and i translate (with google help from Japanese to English and from English to french by myself) then i post the translation here in this issue even it's closed and you @tetsuo you deal with it to update GPlay's language localization's page. Are you ok ? or any other solution ?

**Comment by auge8472** [comment]
> If you have complaints please fork and deal with it yourself

Hmm, a fork is o.k., because that's the common way to handle pull requests. But what do you mean with "deal with it yourself"? I would expect to set a text file with the translated changelog beside your original in japanese language.

@H-F-M: A fork, where you only change the translations of the changelog (like described before) is IMHO more fitting than to put the translations into this (somewhen) closed issue.

**Comment by H-F-M** [comment]
Example for v0.7.5:

1.Vérification de la possibilité de changer le compte d'édition dans les tests du "custom notification listener". Le copié/collé est définit sur "texte seulement".
2.Réorganisation du menu paramètres de l'application.
3.Ajout d'un compte utilisé par défaut lorsque le mode tablette est actif.
4.Changement de compte dans la fenêtre d'envoie de toot même lors d'une réponse est possible.

I'm not sure of the good translation for the [1] cause Google does not translate correctly and says incomprehensible things.

@auge8472 you can write in this issue even issue is closed that what i mean.
i'm open to any other suggestion like text file with pull request system.

"deal with it yourself" seems to be "find solution yourself" ^^

**Comment by tateisu** [comment]
2 users blocked.

**Comment by tateisu** [comment]
日本語の分かる人向けに説明します。

Playストアの「このリリースの新機能 」は「リリース後に編集する」ことができません。
なので「このリリースの新機能 」を多国語化しようとすると
- 自分で翻訳する
- 誰かに翻訳を頼んで出来上がるのを待つ
しかありません。
SubwayTooterの場合は個人で開発してることもあり、どちらの対応も私の手に余ると考えています。
別の誰かが別の場所で新機能の翻訳を行ってくれたらいいなあ、ていうかその程度が限界だと思います。
議論の中でも「私がサポートできる範囲を超えている」と表明しているんですが聞き入れてもらえなかったようです。
issueをissue以外の用途に使うようなことまで書かれてたので、こりゃムリだと思ってブロックしました。
