### ISSUE TITLE
Changing font color

### ISSUE THREAD

**Issue by averageunicorn** [tateisu/SubwayTooter#53]
As it is, reading in Subway Tooter is a strain on my eyes, because the text is too small and too light / low-contrast. It'd be great to have an option to adjust font color and size.

**Comment by jfmcbrayer** [comment]
You can adjust the text size under app settings, and you can adjust the font color in each tab's settings (I'd rather be able to adjust the default, but at least it's possible).

**Comment by averageunicorn** [comment]
Ah, great, adjusting the size seems to have been added since I last tried the app. Thanks for letting me know!

The tabs only have settings for header colors and background color of the column. Not for the color of toot text. (version 1.0.8)

**Comment by tateisu** [comment]
added on v1.1.4
