### ISSUE TITLE
Bold text lost when specifying a custom font

### ISSUE THREAD

**Issue by jfmcbrayer** [tateisu/SubwayTooter#56]
Normally, the display name on toots is displayed in bold.

I have tried a couple of ttf fonts as the font for Subway Tooter. They only contain the "normal" font variant, but I have the bold, italic, and bold italic variants of those fonts in the same folder with them. It would be good to either have the bold font automatically discovered, or to be able to specify a bold font in application settings.

**Comment by tateisu** [comment]
implemented on 1.3.2
