### ISSUE TITLE
Option to show whole image, scaled

### ISSUE THREAD

**Issue by alanz** [tateisu/SubwayTooter#57]
At the moment an image is scaled to take up the full width, and then limited in height, so you only see a strip through the middle.

Would it be possible to add an option to scale the image so the whole thing could be seen in the time-line, limited by a reasonable vertical dimension. Thus a portrait image would still show up, but not take up the full horizontal width.

**Comment by tateisu** [comment]
do you talk about the thumbnail of media attachments ?
please check "Don\'t crop media thumbnail (app restart required)" in app setting.

**Comment by alanz** [comment]
Yes, that does it. Thanks for the quick reply.

And I love the app, thanks for doing it.

**Comment by tateisu** [comment]
I guess what you are looking for is that the app dynamically changes 
the height of the thumbnail frame that matches aspect information of the attached media.

There are some reasons why this app does not so, to put it briefly, 
this app gives priority to performance over appearance.

Currently this app avoids sizing thumbnail frame to its image, In contrast, this app sizing thumbnail image to its frame.
User can switch "centerCrop" or "fitCenter" attribute for ImageView#setScaleType().

One of the reasons is to facilitate layout.
thumbnail frame width depends on the number of media attachment.
but the width is not fixed until the view layout is completed.
Your proposal requires more layout step or more complicated calculations to make layout parameter.

One of the reasons is lack of aspect information of media attachment in some case.
- old toots that is made in old mastodon.
- toots via "Mastodon search portal" toot search API.

I am sorry that I could not be helpful.

**Comment by alanz** [comment]
No, you were helpful.

Setting  "Don't crop media thumbnail (app restart required)" changed it to what I am looking for, which is basically to be able to see the whole image, and I can click on it if there is a detail I want to see better.
