### ISSUE TITLE
Add option to disable auto-refresh behavior of conversations after posting

### ISSUE THREAD

**Issue by Skirmisher** [tateisu/SubwayTooter#67]
Currently, after posting a toot, Subway Tooter automatically refreshes all open conversation columns. This is undesirable when many conversations are open, as it causes the app to make many requests in succession and results in the user getting rate-limited by Mastodon. Additionally, this behavior refreshes columns that aren't currently loaded, which seems wasteful when the user hasn't even looked at those yet.

I would appreciate the addition of an option to disable this behavior, so that no conversations are automatically refreshed after posting.

Thanks for your time and your work on this app :)

**Comment by tateisu** [comment]
ST already have similar setting item.  I think that you will be satisfied using this setting, or do you want a more special behavior?

![screenshot_20180208-125013](https://user-images.githubusercontent.com/333944/35954745-d12417d8-0cce-11e8-8962-f9d3202dc6ef.png)

**Comment by Skirmisher** [comment]
You're right, my mistake. It's confusing since "Disable auto-refresh when returning to the app" overrides that setting. Regardless, this makes it so the timelines refresh but the other columns don't, so thank you ^^;
