### ISSUE TITLE
crash on toots that contain just a U+00AD SOFT HYPHEN

### ISSUE THREAD

**Issue by abochmann** [tateisu/SubwayTooter#69]
Subway Tooter crashes when trying to load this toot: https://cybre.space/@chr/99821978136424081

**Comment by tateisu** [comment]
Reproduced on Nexus 5 (Android 6.0.1)

adb log
https://gist.github.com/tateisu/e2f12e54ef6e05edfa3220f3e2c26a52

**Comment by tateisu** [comment]
reference
- https://github.com/TwidereProject/Twidere-Android/issues/449
- http://2012-2013.chriskrycho.com/web/psa-android-browser-and-soft-hyphens/

**Comment by tateisu** [comment]
Workaround added on
https://github.com/tateisu/SubwayTooter/commit/87d5d78de5acf2899d5627ef09d9aabfa5ec3e97
https://github.com/tateisu/SubwayTooter/releases/tag/v2.3.4
