### ISSUE TITLE
Opening large threads may cause temporary account block

### ISSUE THREAD

**Issue by ghost** [tateisu/SubwayTooter#71]
If the user opens a few big threads or one very large thread like this – https://retro.social/@ajroach42/99882571926573176 – in a five minute period, SubwayTooter sometimes reaches the API request limit and use of the account is temporarily blocked.

**Comment by tateisu** [comment]
Main reason is retrieving "preview card" information for each toots in conversation.
Mastodon does not provide API that can get card information for multiple toots at once.
If we want to solve it on client side, it is necessary to set limits on acquisition of card information.
But we must consider what criteria to do it.

**Comment by tateisu** [comment]
for quick fix, "don't retrieve preview card" is added to app setting - behavior section.
https://github.com/tateisu/SubwayTooter/releases/tag/v2.4.3

**Comment by tateisu** [comment]
since mastodon 2.6.0, each status includes preview card information and ST alsready support it.
this problem no longer reproduced.
