### ISSUE TITLE
Tap column icon to scroll to top feature

### ISSUE THREAD

**Issue by Kjwon15** [tateisu/SubwayTooter#74]
![screenshot_20180707-234355](https://user-images.githubusercontent.com/5047683/42412099-f5954884-8240-11e8-8666-a25bc6feece6.png)
Currently, ST has scroll to top feature by tapping on column's title (upper red circle on screenshot).
By the way, most apps have scroll to top feature by tapping tab icon (bottom red circle on screenshot).

It would be nice if ST has this feature to improve UX.

**Comment by tateisu** [comment]
Sometimes that request comes out, but I think it will lead misoperation.
The bottom of the screen is easy to reach by fingers, but also increases the number of misoperation. 
After the scroll position is inadvertently lost, there is no way to resume the before position.

**Comment by tateisu** [comment]
it's added on https://github.com/tateisu/SubwayTooter/releases/tag/v2.6.3
