### ISSUE TITLE
共有インテントに含まれるテキストか画像どちらか片方しか受け付けない

### ISSUE THREAD

**Issue by geckour** [tateisu/SubwayTooter#75]
テキストと画像(Uri)の両方を含む共有インテントについて考慮されておらず、Uriが存在する時点でテキストはハンドルされず破棄されている

**Comment by tateisu** [comment]
動作確認手順をお知らせください。どんなアプリからどのように送ると再現できるのでしょうか。

**Comment by geckour** [comment]
https://github.com/geckour/NowPlaying4Droid/blob/master/app/src/main/java/com/geckour/nowplaying4gpm/ui/SharingActivity.kt#L77-L92
読み辛いかと思いますが、このように `EXTRA_TEXT` と `EXTRA_STREAM` の両方を指定し、typeに `"image/*"`、`image/jpeg`などを指定した `Intent` を送信した場合に `EXTRA_STREAM` のみがハンドリングされ、 `EXTRA_TEXT` は破棄されます。

**Comment by tateisu** [comment]
動作確認のためにこちらでテストアプリを書けと仰ってるのでしょうか。
