### ISSUE TITLE
Translate SubwayTooter

### ISSUE THREAD

**Issue by BoFFire** [tateisu/SubwayTooter#77]
Hi,
I started to translate SubwayTooter to arabic (RTL language). Can we ask Čihař to host the translation of the project ? :)

https://weblate.org
Regards,

**Comment by tateisu** [comment]
![image](https://user-images.githubusercontent.com/333944/44628686-ce301b00-a97f-11e8-94cb-beddfc1a1061.png)

**Comment by tateisu** [comment]
https://support.weblate.org/ # 228 
[support.weblate.org #228] [Hosted Weblate] Hosting request for Subway Tooter

**Comment by BoFFire** [comment]
Nice, thank you :)

**Comment by BoFFire** [comment]
Ping @nijel

**Comment by tateisu** [comment]
seems https://hosted.weblate.org/projects/subway-tooter/  is open,

but I can't input text to text area.

![image](https://user-images.githubusercontent.com/333944/44892476-f8872d00-ad1f-11e8-9396-3b084cd1a44d.png)

**Comment by BoFFire** [comment]
Thank you @tateisu @nijel \o/ Rock n Roll ! ^-^
