### ISSUE TITLE
Firebase analytics

### ISSUE THREAD

**Issue by BoFFire** [tateisu/SubwayTooter#78]
Hi :)
A lot of users may want don't have this Firebase analytics included.

Check Exodus Report : https://reports.exodus-privacy.eu.org/reports/25391/

**Comment by tateisu** [comment]
this app uses Firebase cloud messaging for push messaging, but does not use any analytics.

please check app/build.gradle for dependency of this app.

**Comment by tateisu** [comment]
The dependencies of firebase messaging library become fewer than before.
The analytics code might be decreased.
but i think some core code is still required for messaging function.

**Comment by IzzySoft** [comment]
@tateisu you might wish to take a look at [my snippet](https://gitlab.com/-/snippets/1896503#push) for alternative push services (and more). I'd recommend @UnifiedPush – for the Playstore release you could bundle it with their FCM distributor (so no changes for your users there), while letting users of "ungoogled devices" chose the [Push Client/Manager](https://android.izzysoft.de/applists/category/named/network_push) they prefer.

As for FCM and Firebase Analytics: your app still has the latter included. You will have to explicitly disable it for the code to be removed. But should you decide for UP, that question might become moot :wink:

**Comment by IzzySoft** [comment]
I'd assume all of them (that's up to the "distributor" with UnifiedPush – I've got no idea how the other two replacements work as I never used them). Apart from being non-free (and thus tainting FOSS apps), FCM is simply not available on ungoogled devices – which is what makes UnifiedPush much preferable. For those preferring FCM, there's always the FCM distributor.

**Comment by tateisu** [comment]
- It requires a complete rewrite of the app server.
- It requires an additional FCM relay server to be built.
- I'm not going to offer ST's "noFcm" build. A single build that can be updated to each other through the Play Store version and other distribution channels is my preferred for distribution.

**Comment by tateisu** [comment]
The trend about de-Google is not so much felt in Japan.
And ST users are heavily biased towards Japan. 
According to Play Store stats, 2348 of the 4062 users are from the Japan region. 
I don't have statistics on the number of installs via F-droid or GitHub.
in this situation, it's a heavy burden for me to spend many time for de-Google.

**Comment by tateisu** [comment]
UnifiedPush receives notifications via any external app, but there is no mechanism to check if the received message can be trusted. If a message is sent from an external app that the user hasn't selected, they won't notice it. If the access to the server increases due to the malicious Intent, the server side rate-limit will be applied and it will be painful. 
Is it a user-acceptable risk?

**Comment by tateisu** [comment]
(This is a memo, not a discussion)
The data sent by Mastodon to the app server via WebPush is signed and contains an HTTP header for its verification.
However, if the app server formats the data to include it all, it may not fit in the payload size allowed by the Push Provider.
To avoid this problem, the app server becomes a data store, and if the data is too long, the app serverneed to change the data sent from the app server to the app to "URL that can be use to get the data".

(これは議論ではなくメモです)
MastodonからWebPushでアプリサーバに送られるデータには署名があり、その検証のためのHTTPヘッダを含みます。
ところがアプリサーバがその全てを含む形にデータを整形すると、それはPush Provider が許容するペイロードサイズに収まらないことがあります。
この問題を回避するにはアプリサーバがデータストアとなり、データが長すぎる場合にはアプリサーバからアプリに送り出すデータを「データを取得できるURL」に変更する必要があります。

**Comment by IzzySoft** [comment]
@tateisu I'm no dev, so I have no idea about the internals or how to implement. I know a few apps using UP, and I didn't hear about any problems they were facing. As for "trend": True, I cannot tell about JP. But for me personally, one of the reasons I avoid to install/use an app is that it contains Firebase (or any other proprietary components like that, e.g. GMS or, worse, Facebook SDK etc).

**Comment by BoFFire** [comment]
Updated about using UnifiedPush : https://fosstodon.org/@unifiedpush/109691465419893051
