### ISSUE TITLE
Publish APK on Github?

### ISSUE THREAD

**Issue by IzzySoft** [tateisu/SubwayTooter#8]
Would you mind attaching the `.apk` to the corresponding `releases/` here at Github, so folks without Playstore access get a chance to try the app? Thanks in advance!

**Comment by tateisu** [comment]
Strictly, this app relies on Chrome Custom Tabs. When browsing attached media, the application first calls Chrome Custom Tabs with the intent that specified the package name, and if it fails it opens another application without specifying the package name.
Therefore, it is not that comfortable to use in an environment where the Google application is not installed.

**Comment by tateisu** [comment]
https://github.com/tateisu/SubwayTooter/releases/tag/v0.3.9

I tried to upload it.
However, I will not make this a routine for every release.

**Comment by IzzySoft** [comment]
Thanks! If you'd do that for at least "major releases", that would be great. Everytime you do, it will be [updated here](https://apt.izzysoft.de/fdroid/index/apk/jp.juggler.subwaytooter) within 24h – so Playstore-less people can use the F-Droid client to stay updated.

PS: Also just added your app to my list of [Clients für Mastodon](https://android.izzysoft.de/applists/category/named/network_twitter#group_1113) to make it easier to find :smile_cat:
