### ISSUE TITLE
Accessibility: tag completion suggestions should use PascalCase

### ISSUE THREAD

**Issue by ryliejamesthomas** [tateisu/SubwayTooter#92]
Hi :)

When screen readers read tags that are multiple words joined together they will try to read them as a single word unless you use capital letters to differentiate. For example the tag #blacklivesmatter will be read as one word, whereas #BlackLivesMatter will be read as three distinct words.

When writing tags in Subway Tooter you get handy suggestions so you don't have to write out the whole tag, but I would love to see those suggestions capitalise each word (AKA PascalCase).

Is this possible?

**Comment by tateisu** [comment]
Mastodon tries to make the case of tag string all lowercase rather. 
That is because they store it in the database so that they can identify tags.
Since the tag list included in the metadata of the toots is all lowercase letters, ST can not learn case.
But ST learns the case of tags when you post.

**Comment by ryliejamesthomas** [comment]
Thanks for the information.

I guess I'll just have to post with tags more often :3
