### ISSUE TITLE
タブレット版簡易投稿からMisskeyへ投稿できない

### ISSUE THREAD

**Issue by miyacorata** [tateisu/SubwayTooter#97]
タブレット版の簡易投稿バーからMisskeyインスタンスに宛てて投稿しようとした場合、`NotFound(HTTP 404)`が返却され投稿できませんでした

通常の投稿ボタンを用いたり、スマホ版からは簡易投稿ができることを確認しています

推定ですが、宛先がMisskeyでもMastodonのAPIを叩こうとしている可能性が考えられます

## notes
* Fire OS 5.3.6.4 (Android 5.1ベース)
* Subway Tooter 3.4.4

**Comment by tateisu** [comment]
再現に必要な情報が不足しているので何とも言えません。
簡易投稿と通常投稿はほぼ同じコードを用いていますので、投稿に選択されたアカウントがあなたが想像しているものと異なるのだと思います。
