### ISSUE TITLE
Local instance @ mention issue

### ISSUE THREAD

**Issue by dahlterm** [tateisu/SubwayTooter#98]
Some instances, such as my home instance on sleeping.town, present the login UI and other API stuff on a seperate URL as the instance's federation URL (mastodon.sleeping.town is what the app uses to connect, for instance)

however, this means that when @ ing users on the same instance as me, it uses mastodon.sleeping.town, instead of sleeping.town

what is confusing, is this second @ is unnecessary (at least for mastodon, cannot speak for pleroma or other), so it can be removed entirely when on the same instance, to resolve this issue.

**Comment by tateisu** [comment]
"mention to a local user" may change to a remote user because ST's post composition can change account that used to post a toot.

also, currently ST does not support instances that has different host name for instance and API.

**Comment by krisstinya** [comment]
Guess I won't be able to use your software anymore. 

I don't mean to be bitter, but I see _many_ ways to fix this.

- add the @ (instance name) on account switch (your software will know the instance thanks to already knowing that account's instance, and thus be able to resolve this problem while still supporting correct @ mentions when switching between accounts)
- simply provide a toggle in the options that allows for naive behaviour that won't let you switch accounts and maintain correct mentions (this one is even easier!)

but instead you presumed i didn't know how your app works, and said "not supported" which feels a bit insulting

I'm sorry for wasting both our time.

**Comment by tateisu** [comment]
https://github.com/tateisu/SubwayTooter/releases/tag/v4.2.1
This beta release includes detection that the API host name and ActivityPub domain name are different.
(please find APK file in assets in release page, also it requires remove and re-add the account from the app).
